  CREATE OR REPLACE PROCEDURE CPM_SP_M2M_ARP_BD_M_PHASE2(
      P_SCENARIO   IN VARCHAR2
    , P_PERIODO    IN VARCHAR2
    , P_AZIENDA    IN VARCHAR2
    , SESSION_USER IN VARCHAR2
  ) AS
    /**************************************************************************
    最后更新时间：20261008
    上一版本信息：
    名称：CPM_SP_M2M_ARP_BD_M_PHASE2
    用途：ARPM02坏账计算表 STEP1坏账计提基数、STEP2坏账计算、STEP3坏账分摊
    源表：AW_MR9_ARPM01_000001、AW_MR9_ARPM02_000001、AW_MR6_ARPINS_000001、AW_RUL_ARPBDR_000001、DWD_FI_MR_ARAP_SUM_MI
    目标表：AW_MR9_ARPM02_000001
    逻辑文档：经分二期-应收-数据模型详细设计文档.xlsx
    特殊逻辑：三段按 STEP1 -> STEP2 -> STEP3 顺序执行；PROVENIENZA 不更新。

    版本信息：最新修改记录放最上面
      20261013 STEP2 坏账计算的BD_1_AMT至BD_15_AMT统一保留两位小数
      20261012 STEP2 配置表按客商、科目匹配并在配置源内去重，保持 MERGE ON 仅按OID
      20261011 STEP1至STEP3 全链路按公司、客商、科目粒度处理，MERGE ON统一按OID匹配
      20261010 STEP1 第一段按公司、客商、科目粒度执行 FIFO 并回写
      20261009 修复 STEP1 多明细行账龄累计重复导致 FIFO 扣减放大
      20261009 按真实配置表结构修正 STEP2 客户匹配、有效期及1-9比例
      20261009 修复公司范围空值判断及 STEP2 账龄基数字段覆盖
      20261009 按三个坏账设计页修复规则表、返利扣减、1-15账龄、个别认定状态、重跑清零及异常边界
      20261008 STEP3 将 AGE_ALLOC_0_AMT 改为各账龄分摊金额合计，并统一在 S 查询中计算回写字段
      20261008 日志按 STEP1、STEP2、STEP3 分段记录，成功路径最后统一提交并优化排版
      20261008 按最新设计文档合并坏账 STEP1、STEP2、STEP3，并完善账龄分摊逻辑
      20261008 新增 ARPM02 坏账计算表 STEP2 坏账计算过程

    手工执行：CALL CPM_SP_M2M_ARP_BD_M_PHASE2('2026ACT','08','6800','USER');
    **************************************************************************/
    V_SCENARIO       VARCHAR2(30);
    V_PERIODO        VARCHAR2(30);
    V_YEARMONTH      VARCHAR2(10);
    V_PREV_YEARMONTH VARCHAR2(10);
    V_LM_SCENARIO    VARCHAR2(30);
    V_LM_PERIODO     VARCHAR2(2);
    V_AZIENDA        VARCHAR2(4000);
    V_SESSION_ID     NUMBER;
    V_ERROR_COD      NUMBER;
    V_ERROR_MSG      VARCHAR2(4000);
  BEGIN
    V_SESSION_ID := SYS_CONTEXT('USERENV', 'SESSIONID');
    V_SCENARIO := P_SCENARIO;
    V_PERIODO := LPAD(P_PERIODO, 2, '0');
    V_YEARMONTH := SUBSTR(V_SCENARIO, 1, 4) || V_PERIODO;
    V_PREV_YEARMONTH := TO_CHAR(ADD_MONTHS(TO_DATE(V_YEARMONTH || '01', 'YYYYMMDD'), -1), 'YYYYMM');
    V_LM_SCENARIO := SUBSTR(V_PREV_YEARMONTH, 1, 4) || SUBSTR(V_SCENARIO, 5);
    V_LM_PERIODO := SUBSTR(V_PREV_YEARMONTH, 5, 2);

    DELETE FROM SESSION_AZIENDA_LIST
    WHERE SESSION_ID = V_SESSION_ID;
    DELETE FROM SESSION_V_REF_AZIENDA
    WHERE SESSION_ID = V_SESSION_ID;

    INSERT INTO SESSION_V_REF_AZIENDA(
        SESSION_ID, HIE, NODE, ELEM
    )
    SELECT V_SESSION_ID, HIE, NODE, ELEM
      FROM TGK_FIMA_HISENSE.V_REF_AZIENDA;

    INSERT INTO SESSION_AZIENDA_LIST(
        SESSION_ID, ELEM
    )
    SELECT DISTINCT V_SESSION_ID, ELEM
      FROM SESSION_V_REF_AZIENDA
    WHERE HIE = '10'
      AND (INSTR(',' || P_AZIENDA || ',', ',' || ELEM || ',') > 0
        OR INSTR(',' || P_AZIENDA || ',', ',' || NODE || ',') > 0
        OR P_AZIENDA = 'ALL')
      AND ELEM IN (
            SELECT COD_AZIENDA
              FROM TGK_FIMA_HISENSE.AW_RUL_DWMCRS_000001
              WHERE ARP_FLAG = 'Y'
                AND VALID_FR <= V_YEARMONTH
                AND NVL(VALID_TO, '999999') >= V_YEARMONTH
                AND COD_CONTO = 'ZAW_D2M_IN'
      )
      AND ELEM NOT IN (
            SELECT COD_AZIENDA
              FROM TGK_FIMA_HISENSE.AW_RUL_DWMCRS_000001
              WHERE ARP_FLAG = 'Y'
                AND COD_SCENARIO = V_SCENARIO
                AND COD_PERIODO = V_PERIODO
                AND COD_CONTO = 'ZAW_D2M_LOCK'
      );

    SELECT LISTAGG(ELEM, ',') WITHIN GROUP (ORDER BY ELEM)
      INTO V_AZIENDA
      FROM (
        SELECT DISTINCT ELEM
          FROM SESSION_AZIENDA_LIST
        WHERE SESSION_ID = V_SESSION_ID
      );

    INSERT INTO ZTAB_CPM_LOG(
        CPM, STEP, EXECTIME, CREATEBY, COD_SCENARIO, COD_PERIODO, COD_AZIENDA
    ) VALUES (
        'CPM_SP_M2M_ARP_BD_M_PHASE2', 'BEGIN 开始执行', SYSDATE, SESSION_USER,
        V_SCENARIO, V_PERIODO, V_AZIENDA
    );
    COMMIT;
    -- ============================================================================
    -- STEP1：坏账计提基数
    -- 以 BCY_ADJ_INCL_1~15 为账龄基础；垫资从长账龄开始冲减，负数按公司+客户+科目
    -- 的账龄顺序冲减正数，最后按原行正数金额比例回写到明细行。
    -- ============================================================================
    MERGE INTO AW_MR9_ARPM02_000001 T
    USING (
      WITH
      -- 当前期间目标表行及垫资、投保信息。
      BASE_DATA AS (
        SELECT A.OID, A.COD_AZIENDA, A.CUST_CODE, A.COD_CONTO, A.COD_DEST2
            , A.COD_CATEGORIA
            , A.BCY_ADJ_INCL_1_AMT, A.BCY_ADJ_INCL_2_AMT, A.BCY_ADJ_INCL_3_AMT
            , A.BCY_ADJ_INCL_4_AMT, A.BCY_ADJ_INCL_5_AMT, A.BCY_ADJ_INCL_6_AMT
            , A.BCY_ADJ_INCL_7_AMT, A.BCY_ADJ_INCL_8_AMT, A.BCY_ADJ_INCL_9_AMT
            , A.BCY_ADJ_INCL_10_AMT, A.BCY_ADJ_INCL_11_AMT, A.BCY_ADJ_INCL_12_AMT
            , A.BCY_ADJ_INCL_13_AMT, A.BCY_ADJ_INCL_14_AMT, A.BCY_ADJ_INCL_15_AMT
            , NVL(D.SPC_DSV_DED_AMT, 0) AS SPC_DSV_DED_AMT
            , NVL(R.SPC_REB_DED_AMT, 0) AS SPC_REB_DED_AMT
            , I.INS_COV_DAYS, I.INS_UNCOV_RATIO
          FROM AW_MR9_ARPM02_000001 A
          LEFT JOIN (
            SELECT COD_AZIENDA, COD_CONTO, CUST_CODE, COD_DEST2, SUM(BCY_0_AMT) SPC_DSV_DED_AMT
              FROM AW_MR9_ARPM01_000001
            WHERE COD_SCENARIO = V_SCENARIO AND COD_PERIODO = V_PERIODO
              AND COD_CATEGORIA = 'ZFAMOUNT'
              AND D_ADJ_TYPE = 'ARP_02_001'
              AND COD_AZIENDA IN (SELECT ELEM FROM SESSION_AZIENDA_LIST WHERE SESSION_ID = V_SESSION_ID)
            GROUP BY COD_AZIENDA, COD_CONTO, CUST_CODE, COD_DEST2
          ) D ON D.COD_AZIENDA = A.COD_AZIENDA AND D.COD_CONTO = A.COD_CONTO AND D.CUST_CODE = A.CUST_CODE AND D.COD_DEST2 = A.COD_DEST2
          LEFT JOIN (
            SELECT COD_AZIENDA, COD_CONTO, CUST_CODE, COD_DEST2, SUM(BCY_0_AMT) SPC_REB_DED_AMT
              FROM AW_MR9_ARPM01_000001
            WHERE COD_SCENARIO = V_SCENARIO AND COD_PERIODO = V_PERIODO
              AND COD_CATEGORIA = 'ZFAMOUNT'
              AND D_ADJ_TYPE = 'ARP_02_003'
              AND COD_AZIENDA IN (SELECT ELEM FROM SESSION_AZIENDA_LIST WHERE SESSION_ID = V_SESSION_ID)
            GROUP BY COD_AZIENDA, COD_CONTO, CUST_CODE, COD_DEST2
          ) R ON R.COD_AZIENDA = A.COD_AZIENDA AND R.COD_CONTO = A.COD_CONTO AND R.CUST_CODE = A.CUST_CODE AND R.COD_DEST2 = A.COD_DEST2
          LEFT JOIN (
            SELECT COD_AZIENDA, COD_CONTO, CUST_CODE, MAX(INS_COV_DAYS) INS_COV_DAYS
                , MAX(INS_UNCOV_RATIO) INS_UNCOV_RATIO
              FROM AW_MR6_ARPINS_000001
            WHERE COD_SCENARIO = V_SCENARIO AND COD_PERIODO = V_PERIODO
              AND COD_AZIENDA IN (SELECT ELEM FROM SESSION_AZIENDA_LIST WHERE SESSION_ID = V_SESSION_ID)
            GROUP BY COD_AZIENDA, COD_CONTO, CUST_CODE
          ) I ON I.COD_AZIENDA = A.COD_AZIENDA AND I.COD_CONTO = A.COD_CONTO AND I.CUST_CODE = A.CUST_CODE
        WHERE A.COD_SCENARIO = V_SCENARIO AND A.COD_PERIODO = V_PERIODO
          AND A.COD_AZIENDA IN (SELECT ELEM FROM SESSION_AZIENDA_LIST WHERE SESSION_ID = V_SESSION_ID)
      ),
      -- 将各账龄列转为账龄编号和金额，便于统一执行长账龄优先规则。
      AGE_UNPIVOT AS (
        SELECT *
          FROM BASE_DATA
          UNPIVOT (RAW_AMT FOR AGE_NO IN (
            BCY_ADJ_INCL_1_AMT AS 1, BCY_ADJ_INCL_2_AMT AS 2, BCY_ADJ_INCL_3_AMT AS 3
          , BCY_ADJ_INCL_4_AMT AS 4, BCY_ADJ_INCL_5_AMT AS 5, BCY_ADJ_INCL_6_AMT AS 6
          , BCY_ADJ_INCL_7_AMT AS 7, BCY_ADJ_INCL_8_AMT AS 8, BCY_ADJ_INCL_9_AMT AS 9
          , BCY_ADJ_INCL_10_AMT AS 10, BCY_ADJ_INCL_11_AMT AS 11, BCY_ADJ_INCL_12_AMT AS 12
          , BCY_ADJ_INCL_13_AMT AS 13, BCY_ADJ_INCL_14_AMT AS 14, BCY_ADJ_INCL_15_AMT AS 15)) UNPIVOT_ROWS
      ),
      -- 按账龄倒序计算每行之前已占用的正数金额。
      AGE_PROGRESS AS (
        SELECT AGE_UNPIVOT.*, GREATEST(NVL(RAW_AMT, 0), 0) POS_AMT
            , SUM(GREATEST(NVL(RAW_AMT, 0), 0)) OVER
                (PARTITION BY OID, COD_CONTO ORDER BY AGE_NO DESC ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING) PRIOR_POS
          FROM AGE_UNPIVOT
      ),
      -- 根据垫资金额计算各账龄段实际可扣减金额。
      DEDUCTED_AGE AS (
        SELECT AGE_PROGRESS.*, GREATEST(NVL(SPC_DSV_DED_AMT, 0) + NVL(SPC_REB_DED_AMT, 0) - NVL(PRIOR_POS, 0), 0) DED_LEFT
            , GREATEST(NVL(RAW_AMT, 0), 0)
              - LEAST(GREATEST(NVL(RAW_AMT, 0), 0), GREATEST(NVL(SPC_DSV_DED_AMT, 0) + NVL(SPC_REB_DED_AMT, 0) - NVL(PRIOR_POS, 0), 0)) ADJ_POS
          FROM AGE_PROGRESS
      ),
      -- 汇总公司、客户、账龄的负数待分摊金额；正数账龄合计在下一层按账龄唯一汇总。
      AGE_SUMMARY AS (
        SELECT DEDUCTED_AGE.*
            , SUM(CASE WHEN RAW_AMT < 0 THEN -RAW_AMT ELSE 0 END) OVER
                (PARTITION BY COD_AZIENDA, CUST_CODE, COD_CONTO) NEG_TOTAL
          FROM DEDUCTED_AGE
      ),
      -- 先按公司、客户、科目、账龄汇总，避免同一账龄多个明细行重复参与 FIFO 累计。
      AGE_TOTAL AS (
        SELECT COD_AZIENDA, CUST_CODE, COD_CONTO, AGE_NO
            , SUM(ADJ_POS) AGE_POS
            , MAX(NEG_TOTAL) NEG_TOTAL
          FROM AGE_SUMMARY
         GROUP BY COD_AZIENDA, CUST_CODE, COD_CONTO, AGE_NO
      ),
      -- 按长账龄优先顺序计算每个账龄前已存在的正数金额。
      AGE_FIFO_TOTAL AS (
        SELECT AGE_TOTAL.*
            , SUM(AGE_POS) OVER
                (PARTITION BY COD_AZIENDA, CUST_CODE, COD_CONTO ORDER BY AGE_NO DESC
                  ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING) OLDER_POS
          FROM AGE_TOTAL
      ),
      -- 将账龄级 FIFO 结果回接明细行，保持后续按原行正数比例回写。
      AGE_FIFO AS (
        SELECT AGE_SUMMARY.*, AGE_FIFO_TOTAL.AGE_POS, AGE_FIFO_TOTAL.OLDER_POS
          FROM AGE_SUMMARY
          JOIN AGE_FIFO_TOTAL
            ON AGE_FIFO_TOTAL.COD_AZIENDA = AGE_SUMMARY.COD_AZIENDA
           AND AGE_FIFO_TOTAL.CUST_CODE = AGE_SUMMARY.CUST_CODE
           AND AGE_FIFO_TOTAL.COD_CONTO = AGE_SUMMARY.COD_CONTO
           AND AGE_FIFO_TOTAL.AGE_NO = AGE_SUMMARY.AGE_NO
      ),
      -- 计算负数冲减后的账龄金额及行内分摊比例。
      AGE_ALLOCATED AS (
        SELECT AGE_FIFO.*, AGE_POS - LEAST(AGE_POS, GREATEST(NEG_TOTAL - NVL(OLDER_POS, 0), 0)) FINAL_AGE_POS
            , CASE WHEN AGE_POS <> 0 THEN ADJ_POS / AGE_POS ELSE 0 END POS_RATE
          FROM AGE_FIFO
      ),
      -- 将账龄明细重新汇总为目标表的一行及各计提基数。
      BASE_RESULT AS (
        SELECT OID, COD_CONTO, MAX(SPC_DSV_DED_AMT) SPC_DSV_DED_AMT, MAX(SPC_REB_DED_AMT) SPC_REB_DED_AMT
            , MAX(INS_COV_DAYS) INS_COV_DAYS, MAX(INS_UNCOV_RATIO) INS_UNCOV_RATIO
            , SUM(CASE WHEN AGE_NO = 1 THEN FINAL_AGE_POS * POS_RATE ELSE 0 END) BD_BASE_1_AMT
            , SUM(CASE WHEN AGE_NO = 2 THEN FINAL_AGE_POS * POS_RATE ELSE 0 END) BD_BASE_2_AMT
            , SUM(CASE WHEN AGE_NO = 3 THEN FINAL_AGE_POS * POS_RATE ELSE 0 END) BD_BASE_3_AMT
            , SUM(CASE WHEN AGE_NO = 4 THEN FINAL_AGE_POS * POS_RATE ELSE 0 END) BD_BASE_4_AMT
            , SUM(CASE WHEN AGE_NO = 5 THEN FINAL_AGE_POS * POS_RATE ELSE 0 END) BD_BASE_5_AMT
            , SUM(CASE WHEN AGE_NO = 6 THEN FINAL_AGE_POS * POS_RATE ELSE 0 END) BD_BASE_6_AMT
            , SUM(CASE WHEN AGE_NO = 7 THEN FINAL_AGE_POS * POS_RATE ELSE 0 END) BD_BASE_7_AMT
            , SUM(CASE WHEN AGE_NO = 8 THEN FINAL_AGE_POS * POS_RATE ELSE 0 END) BD_BASE_8_AMT
            , SUM(CASE WHEN AGE_NO = 9 THEN FINAL_AGE_POS * POS_RATE ELSE 0 END) BD_BASE_9_AMT
            , SUM(CASE WHEN AGE_NO = 10 THEN FINAL_AGE_POS * POS_RATE ELSE 0 END) BD_BASE_10_AMT
            , SUM(CASE WHEN AGE_NO = 11 THEN FINAL_AGE_POS * POS_RATE ELSE 0 END) BD_BASE_11_AMT
            , SUM(CASE WHEN AGE_NO = 12 THEN FINAL_AGE_POS * POS_RATE ELSE 0 END) BD_BASE_12_AMT
            , SUM(CASE WHEN AGE_NO = 13 THEN FINAL_AGE_POS * POS_RATE ELSE 0 END) BD_BASE_13_AMT
            , SUM(CASE WHEN AGE_NO = 14 THEN FINAL_AGE_POS * POS_RATE ELSE 0 END) BD_BASE_14_AMT
            , SUM(CASE WHEN AGE_NO = 15 THEN FINAL_AGE_POS * POS_RATE ELSE 0 END) BD_BASE_15_AMT
          FROM AGE_ALLOCATED GROUP BY OID, COD_CONTO
      ) SELECT BASE_RESULT.*, BD_BASE_1_AMT + BD_BASE_2_AMT + BD_BASE_3_AMT + BD_BASE_4_AMT
                + BD_BASE_5_AMT + BD_BASE_6_AMT + BD_BASE_7_AMT + BD_BASE_8_AMT
                + BD_BASE_9_AMT + BD_BASE_10_AMT + BD_BASE_11_AMT + BD_BASE_12_AMT
                + BD_BASE_13_AMT + BD_BASE_14_AMT + BD_BASE_15_AMT BD_BASE_0_AMT
        FROM BASE_RESULT
    ) S ON (T.OID = S.OID)
    WHEN MATCHED THEN UPDATE SET
        T.SPC_DSV_DED_AMT = S.SPC_DSV_DED_AMT, T.SPC_REB_DED_AMT = S.SPC_REB_DED_AMT, T.INS_COV_DAYS = S.INS_COV_DAYS
      , T.INS_UNCOV_RATE = S.INS_UNCOV_RATIO, T.BD_BASE_0_AMT = S.BD_BASE_0_AMT
      , T.BD_BASE_1_AMT = S.BD_BASE_1_AMT, T.BD_BASE_2_AMT = S.BD_BASE_2_AMT, T.BD_BASE_3_AMT = S.BD_BASE_3_AMT
      , T.BD_BASE_4_AMT = S.BD_BASE_4_AMT, T.BD_BASE_5_AMT = S.BD_BASE_5_AMT, T.BD_BASE_6_AMT = S.BD_BASE_6_AMT
      , T.BD_BASE_7_AMT = S.BD_BASE_7_AMT, T.BD_BASE_8_AMT = S.BD_BASE_8_AMT, T.BD_BASE_9_AMT = S.BD_BASE_9_AMT
      , T.BD_BASE_10_AMT = S.BD_BASE_10_AMT, T.BD_BASE_11_AMT = S.BD_BASE_11_AMT, T.BD_BASE_12_AMT = S.BD_BASE_12_AMT
      , T.BD_BASE_13_AMT = S.BD_BASE_13_AMT
      , T.BD_BASE_14_AMT = S.BD_BASE_14_AMT
      , T.BD_BASE_15_AMT = S.BD_BASE_15_AMT
      , T.DATEUPD = SYSDATE
      , T.USERUPD = SESSION_USER;

    INSERT INTO ZTAB_CPM_LOG(
        CPM, STEP, EXECTIME, CREATEBY, COD_SCENARIO, COD_PERIODO, COD_AZIENDA
    ) VALUES (
        'CPM_SP_M2M_ARP_BD_M_PHASE2', 'STEP1 坏账计提基数完成', SYSDATE, SESSION_USER,
        V_SCENARIO, V_PERIODO, V_AZIENDA
    );
    COMMIT;
    -- ============================================================================
    -- STEP2：坏账计算
    -- ============================================================================
    -- 清零当前批次个别认定，避免无来源时沿用上次运行结果。
    UPDATE AW_MR9_ARPM02_000001
       SET SPID_0_AMT = 0, SPID_1_AMT = 0, SPID_2_AMT = 0, SPID_3_AMT = 0
         , SPID_4_AMT = 0, SPID_5_AMT = 0, SPID_6_AMT = 0, SPID_7_AMT = 0
         , SPID_8_AMT = 0, SPID_9_AMT = 0, SPID_10_AMT = 0, SPID_11_AMT = 0
         , SPID_12_AMT = 0, SPID_13_AMT = 0, SPID_14_AMT = 0, SPID_15_AMT = 0
     WHERE COD_SCENARIO = V_SCENARIO AND COD_PERIODO = V_PERIODO
       AND COD_AZIENDA IN (SELECT ELEM FROM SESSION_AZIENDA_LIST WHERE SESSION_ID = V_SESSION_ID);
    -- 个别认定按完整业务键聚合后回写，来源存在状态在后续 CTE 中重新判定。
    MERGE INTO AW_MR9_ARPM02_000001 T
    USING (
      SELECT T0.OID, T0.COD_CONTO, SUM(A.BCY_0_AMT) SPID_0_AMT, SUM(A.BCY_1_AMT) SPID_1_AMT
          , SUM(A.BCY_2_AMT) SPID_2_AMT, SUM(A.BCY_3_AMT) SPID_3_AMT, SUM(A.BCY_4_AMT) SPID_4_AMT
          , SUM(A.BCY_5_AMT) SPID_5_AMT, SUM(A.BCY_6_AMT) SPID_6_AMT, SUM(A.BCY_7_AMT) SPID_7_AMT
          , SUM(A.BCY_8_AMT) SPID_8_AMT, SUM(A.BCY_9_AMT) SPID_9_AMT, SUM(A.BCY_10_AMT) SPID_10_AMT
          , SUM(A.BCY_11_AMT) SPID_11_AMT, SUM(A.BCY_12_AMT) SPID_12_AMT, SUM(A.BCY_13_AMT) SPID_13_AMT
          , SUM(A.BCY_14_AMT) SPID_14_AMT, SUM(A.BCY_15_AMT) SPID_15_AMT
        FROM AW_MR9_ARPM02_000001 T0
        JOIN AW_MR9_ARPM01_000001 A 
          ON A.COD_SCENARIO = T0.COD_SCENARIO 
        AND A.COD_PERIODO = T0.COD_PERIODO
        AND A.COD_AZIENDA = T0.COD_AZIENDA 
        AND A.CUST_CODE = T0.CUST_CODE
        AND A.COD_DEST2 = T0.COD_DEST2 
        AND A.COD_CONTO = T0.COD_CONTO
        AND A.NATURE_L3_NAME = T0.NATURE_L3_NAME
      WHERE T0.COD_SCENARIO = V_SCENARIO AND T0.COD_PERIODO = V_PERIODO
        AND T0.COD_AZIENDA IN (SELECT ELEM FROM SESSION_AZIENDA_LIST WHERE SESSION_ID = V_SESSION_ID)
        AND A.COD_CATEGORIA = 'ZFAMOUNT' 
        AND A.D_ADJ_TYPE = 'ARP_02_002'
      GROUP BY T0.OID, T0.COD_CONTO
    ) S ON (T.OID = S.OID)
    WHEN MATCHED THEN UPDATE SET
        T.SPID_0_AMT = S.SPID_0_AMT
      , T.SPID_1_AMT = S.SPID_1_AMT
      , T.SPID_2_AMT = S.SPID_2_AMT
      , T.SPID_3_AMT = S.SPID_3_AMT
      , T.SPID_4_AMT = S.SPID_4_AMT
      , T.SPID_5_AMT = S.SPID_5_AMT
      , T.SPID_6_AMT = S.SPID_6_AMT
      , T.SPID_7_AMT = S.SPID_7_AMT
      , T.SPID_8_AMT = S.SPID_8_AMT
      , T.SPID_9_AMT = S.SPID_9_AMT
      , T.SPID_10_AMT = S.SPID_10_AMT
      , T.SPID_11_AMT = S.SPID_11_AMT
      , T.SPID_12_AMT = S.SPID_12_AMT
      , T.SPID_13_AMT = S.SPID_13_AMT
      , T.SPID_14_AMT = S.SPID_14_AMT
      , T.SPID_15_AMT = S.SPID_15_AMT
      , T.DATEUPD = SYSDATE
      , T.USERUPD = SESSION_USER;

    MERGE INTO AW_MR9_ARPM02_000001 T
    USING (
      WITH
      -- 当前期间目标表行，后续按客商和科目匹配坏账比例配置。
      CALCULATION_SOURCE AS (
        SELECT A.*
          FROM AW_MR9_ARPM02_000001 A
        WHERE A.COD_SCENARIO = V_SCENARIO
          AND A.COD_PERIODO = V_PERIODO
          AND A.COD_AZIENDA IN (
                SELECT ELEM
                  FROM SESSION_AZIENDA_LIST
                  WHERE SESSION_ID = V_SESSION_ID
          )
      ),
      -- 配置源按公司、科目及集团范围前三位建立基础匹配范围，并保留有效期条件。
      -- BATCH_ID即优先级：1为公司+客商，2为公司+性质，3为公司级通用规则。
      -- 同一业务明细只保留最高优先级配置；有效期起始时间及真实配置字段用于并列消歧。
      FORM_RATE_SOURCE AS (
        SELECT OID, COD_AZIENDA, COD_CONTO, CUST_CODE, NATURE_L3_NAME, GRP_SCOPE
            , BD_RATIO_1, BD_RATIO_2, BD_RATIO_3, BD_RATIO_4, BD_RATIO_5
            , BD_RATIO_6, BD_RATIO_7, BD_RATIO_8, BD_RATIO_9
          FROM (
            SELECT A.OID, A.COD_AZIENDA, A.COD_CONTO, A.CUST_CODE, A.NATURE_L3_NAME, A.GRP_SCOPE
                , R.BD_RATIO_1, R.BD_RATIO_2, R.BD_RATIO_3, R.BD_RATIO_4, R.BD_RATIO_5
                , R.BD_RATIO_6, R.BD_RATIO_7, R.BD_RATIO_8, R.BD_RATIO_9
                , ROW_NUMBER() OVER (
                    PARTITION BY A.OID, A.COD_CONTO
                    ORDER BY R.BATCH_ID ASC, R.VALID_FR DESC, NVL(R.VALID_TO, '999999') DESC
                        , R.LOGIC_NAME, R.CUST_CODE, R.CUST_NAME, R.NATURE_L3_NAME
                        , R.BD_RATIO_1 DESC, R.BD_RATIO_2 DESC, R.BD_RATIO_3 DESC
                        , R.BD_RATIO_4 DESC, R.BD_RATIO_5 DESC, R.BD_RATIO_6 DESC
                        , R.BD_RATIO_7 DESC, R.BD_RATIO_8 DESC, R.BD_RATIO_9 DESC
                  ) RATE_RN
              FROM CALCULATION_SOURCE A
              JOIN TGK_FIMA_HISENSE.AW_RUL_ARPBDR_000001 R
                ON R.COD_AZIENDA = A.COD_AZIENDA
               AND R.COD_CONTO = A.COD_CONTO
               AND SUBSTR(R.GRP_SCOPE, 1, 3) = SUBSTR(A.GRP_SCOPE, 1, 3)
               AND (
                    (R.BATCH_ID = 1
                     AND R.CUST_CODE IS NOT NULL
                     AND R.CUST_CODE = A.CUST_CODE)
                 OR (R.BATCH_ID = 2
                     AND R.CUST_CODE IS NULL
                     AND R.NATURE_L3_NAME IS NOT NULL
                     AND R.NATURE_L3_NAME = A.NATURE_L3_NAME)
                 OR (R.BATCH_ID = 3
                     AND R.CUST_CODE IS NULL
                     AND R.NATURE_L3_NAME IS NULL)
               )
             WHERE R.VALID_FR <= V_YEARMONTH
               AND NVL(R.VALID_TO, '999999') >= V_YEARMONTH
               AND R.BATCH_ID IN (1, 2, 3)
          ) R
         WHERE R.RATE_RN = 1
      ),
      -- 按OID和科目关联唯一有效比例配置，避免配置重叠时放大目标行。
      FORM_RATE_SELECTED AS (
        SELECT OID, COD_AZIENDA, COD_CONTO
            , BD_RATIO_1, BD_RATIO_2, BD_RATIO_3, BD_RATIO_4, BD_RATIO_5
            , BD_RATIO_6, BD_RATIO_7, BD_RATIO_8, BD_RATIO_9
          FROM FORM_RATE_SOURCE
      ),
      -- 当前期间坏账计提基数、个别认定金额和计提比例候选数据。
      CALCULATION_BASE AS (
        SELECT A.OID, A.COD_AZIENDA, A.COD_CONTO, A.CUST_CODE, A.COD_DEST2, A.NATURE_L3_NAME, A.GRP_SCOPE
            , A.SPID_1_AMT, A.BD_BASE_1_AMT, A.BD_BASE_2_AMT, A.BD_BASE_3_AMT, A.BD_BASE_4_AMT
            , A.BD_BASE_5_AMT, A.BD_BASE_6_AMT, A.BD_BASE_7_AMT, A.BD_BASE_8_AMT, A.BD_BASE_9_AMT
            , A.BD_BASE_10_AMT, A.BD_BASE_11_AMT, A.BD_BASE_12_AMT, A.BD_BASE_13_AMT, A.BD_BASE_14_AMT
            , A.BD_BASE_15_AMT
            , A.INS_COV_DAYS, A.INS_UNCOV_RATE
            , NVL(INDIVIDUAL_DATA.HAS_INDIVIDUAL, 0) HAS_INDIVIDUAL
            , NVL(INDIVIDUAL_DATA.SPID_1_AMT,0) INDIVIDUAL_1_AMT, NVL(INDIVIDUAL_DATA.SPID_2_AMT,0) INDIVIDUAL_2_AMT
            , NVL(INDIVIDUAL_DATA.SPID_3_AMT,0) INDIVIDUAL_3_AMT, NVL(INDIVIDUAL_DATA.SPID_4_AMT,0) INDIVIDUAL_4_AMT
            , NVL(INDIVIDUAL_DATA.SPID_5_AMT,0) INDIVIDUAL_5_AMT, NVL(INDIVIDUAL_DATA.SPID_6_AMT,0) INDIVIDUAL_6_AMT
            , NVL(INDIVIDUAL_DATA.SPID_7_AMT,0) INDIVIDUAL_7_AMT, NVL(INDIVIDUAL_DATA.SPID_8_AMT,0) INDIVIDUAL_8_AMT
            , NVL(INDIVIDUAL_DATA.SPID_9_AMT,0) INDIVIDUAL_9_AMT, NVL(INDIVIDUAL_DATA.SPID_10_AMT,0) INDIVIDUAL_10_AMT
            , NVL(INDIVIDUAL_DATA.SPID_11_AMT,0) INDIVIDUAL_11_AMT, NVL(INDIVIDUAL_DATA.SPID_12_AMT,0) INDIVIDUAL_12_AMT
            , NVL(INDIVIDUAL_DATA.SPID_13_AMT,0) INDIVIDUAL_13_AMT, NVL(INDIVIDUAL_DATA.SPID_14_AMT,0) INDIVIDUAL_14_AMT
            , NVL(INDIVIDUAL_DATA.SPID_15_AMT,0) INDIVIDUAL_15_AMT
            , NVL(FORM_RATE.BD_RATIO_1,0) BD_RATIO_1, NVL(FORM_RATE.BD_RATIO_2,0) BD_RATIO_2
            , NVL(FORM_RATE.BD_RATIO_3,0) BD_RATIO_3, NVL(FORM_RATE.BD_RATIO_4,0) BD_RATIO_4
            , NVL(FORM_RATE.BD_RATIO_5,0) BD_RATIO_5, NVL(FORM_RATE.BD_RATIO_6,0) BD_RATIO_6
            , NVL(FORM_RATE.BD_RATIO_7,0) BD_RATIO_7, NVL(FORM_RATE.BD_RATIO_8,0) BD_RATIO_8
            , NVL(FORM_RATE.BD_RATIO_9,0) BD_RATIO_9
          FROM CALCULATION_SOURCE A
          LEFT JOIN (
            SELECT COD_AZIENDA, COD_CONTO, CUST_CODE, COD_DEST2, NATURE_L3_NAME
                , COUNT(*) HAS_INDIVIDUAL
                , SUM(BCY_1_AMT) SPID_1_AMT, SUM(BCY_2_AMT) SPID_2_AMT, SUM(BCY_3_AMT) SPID_3_AMT
                , SUM(BCY_4_AMT) SPID_4_AMT, SUM(BCY_5_AMT) SPID_5_AMT, SUM(BCY_6_AMT) SPID_6_AMT
                , SUM(BCY_7_AMT) SPID_7_AMT, SUM(BCY_8_AMT) SPID_8_AMT, SUM(BCY_9_AMT) SPID_9_AMT
                , SUM(BCY_10_AMT) SPID_10_AMT, SUM(BCY_11_AMT) SPID_11_AMT, SUM(BCY_12_AMT) SPID_12_AMT
                , SUM(BCY_13_AMT) SPID_13_AMT, SUM(BCY_14_AMT) SPID_14_AMT, SUM(BCY_15_AMT) SPID_15_AMT
              FROM AW_MR9_ARPM01_000001
            WHERE COD_SCENARIO = V_SCENARIO AND COD_PERIODO = V_PERIODO AND COD_CATEGORIA = 'ZFAMOUNT'
              AND D_ADJ_TYPE = 'ARP_02_002'
            GROUP BY COD_AZIENDA, COD_CONTO, CUST_CODE, COD_DEST2, NATURE_L3_NAME
          ) INDIVIDUAL_DATA ON INDIVIDUAL_DATA.COD_AZIENDA = A.COD_AZIENDA AND INDIVIDUAL_DATA.COD_CONTO = A.COD_CONTO AND INDIVIDUAL_DATA.CUST_CODE = A.CUST_CODE
            AND INDIVIDUAL_DATA.COD_DEST2 = A.COD_DEST2 AND INDIVIDUAL_DATA.NATURE_L3_NAME = A.NATURE_L3_NAME
          LEFT JOIN FORM_RATE_SELECTED FORM_RATE ON FORM_RATE.OID = A.OID
            AND FORM_RATE.COD_CONTO = A.COD_CONTO
      ),
      -- 根据个别认定金额、规则比例和投保未覆盖系数计算1至15账龄坏账。
      BAD_DEBT_CALCULATION AS (
        SELECT CALCULATION_BASE.*
            , CASE WHEN HAS_INDIVIDUAL = 1 THEN INDIVIDUAL_1_AMT ELSE BD_BASE_1_AMT * NVL(BD_RATIO_1,0) * CASE WHEN NVL(INS_COV_DAYS,0) <= 0 THEN 1 WHEN INS_COV_DAYS <= 30 THEN NVL(INS_UNCOV_RATE,1) ELSE 0 END END CALCULATED_1_AMT
            , CASE WHEN HAS_INDIVIDUAL = 1 THEN INDIVIDUAL_2_AMT ELSE BD_BASE_2_AMT * NVL(BD_RATIO_2,0) * CASE WHEN NVL(INS_COV_DAYS,0) <= 0 THEN 1 WHEN INS_COV_DAYS > 30 AND INS_COV_DAYS <= 90 THEN NVL(INS_UNCOV_RATE,1) ELSE 0 END END CALCULATED_2_AMT
            , CASE WHEN HAS_INDIVIDUAL = 1 THEN INDIVIDUAL_3_AMT ELSE BD_BASE_3_AMT * NVL(BD_RATIO_3,0) * CASE WHEN NVL(INS_COV_DAYS,0) <= 0 THEN 1 WHEN INS_COV_DAYS > 90 AND INS_COV_DAYS <= 180 THEN NVL(INS_UNCOV_RATE,1) ELSE 0 END END CALCULATED_3_AMT
            , CASE WHEN HAS_INDIVIDUAL = 1 THEN INDIVIDUAL_4_AMT ELSE BD_BASE_4_AMT * NVL(BD_RATIO_4,0) * CASE WHEN NVL(INS_COV_DAYS,0) <= 0 THEN 1 WHEN INS_COV_DAYS > 180 THEN NVL(INS_UNCOV_RATE,1) ELSE 0 END END CALCULATED_4_AMT
            , CASE WHEN HAS_INDIVIDUAL = 1 THEN INDIVIDUAL_5_AMT ELSE BD_BASE_5_AMT * NVL(BD_RATIO_5,0) END CALCULATED_5_AMT
            , CASE WHEN HAS_INDIVIDUAL = 1 THEN INDIVIDUAL_6_AMT ELSE BD_BASE_6_AMT * NVL(BD_RATIO_6,0) END CALCULATED_6_AMT
            , CASE WHEN HAS_INDIVIDUAL = 1 THEN INDIVIDUAL_7_AMT ELSE BD_BASE_7_AMT * NVL(BD_RATIO_7,0) END CALCULATED_7_AMT
            , CASE WHEN HAS_INDIVIDUAL = 1 THEN INDIVIDUAL_8_AMT ELSE BD_BASE_8_AMT * NVL(BD_RATIO_8,0) END CALCULATED_8_AMT
            , CASE WHEN HAS_INDIVIDUAL = 1 THEN INDIVIDUAL_9_AMT ELSE BD_BASE_9_AMT * NVL(BD_RATIO_9,0) END CALCULATED_9_AMT
            -- 配置表无10至15比例；无个别认定时按当前设计不计算这些账龄。
            , CASE WHEN HAS_INDIVIDUAL = 1 THEN INDIVIDUAL_10_AMT ELSE 0 END CALCULATED_10_AMT
            , CASE WHEN HAS_INDIVIDUAL = 1 THEN INDIVIDUAL_11_AMT ELSE 0 END CALCULATED_11_AMT
            , CASE WHEN HAS_INDIVIDUAL = 1 THEN INDIVIDUAL_12_AMT ELSE 0 END CALCULATED_12_AMT
            , CASE WHEN HAS_INDIVIDUAL = 1 THEN INDIVIDUAL_13_AMT ELSE 0 END CALCULATED_13_AMT
            , CASE WHEN HAS_INDIVIDUAL = 1 THEN INDIVIDUAL_14_AMT ELSE 0 END CALCULATED_14_AMT
            , CASE WHEN HAS_INDIVIDUAL = 1 THEN INDIVIDUAL_15_AMT ELSE 0 END CALCULATED_15_AMT
          FROM CALCULATION_BASE
      ) SELECT OID
          , ROUND(CALCULATED_1_AMT, 2) CALCULATED_1_AMT, ROUND(CALCULATED_2_AMT, 2) CALCULATED_2_AMT
          , ROUND(CALCULATED_3_AMT, 2) CALCULATED_3_AMT, ROUND(CALCULATED_4_AMT, 2) CALCULATED_4_AMT
          , ROUND(CALCULATED_5_AMT, 2) CALCULATED_5_AMT, ROUND(CALCULATED_6_AMT, 2) CALCULATED_6_AMT
          , ROUND(CALCULATED_7_AMT, 2) CALCULATED_7_AMT, ROUND(CALCULATED_8_AMT, 2) CALCULATED_8_AMT
          , ROUND(CALCULATED_9_AMT, 2) CALCULATED_9_AMT, ROUND(CALCULATED_10_AMT, 2) CALCULATED_10_AMT
          , ROUND(CALCULATED_11_AMT, 2) CALCULATED_11_AMT, ROUND(CALCULATED_12_AMT, 2) CALCULATED_12_AMT
          , ROUND(CALCULATED_13_AMT, 2) CALCULATED_13_AMT, ROUND(CALCULATED_14_AMT, 2) CALCULATED_14_AMT
          , ROUND(CALCULATED_15_AMT, 2) CALCULATED_15_AMT
          , ROUND(CALCULATED_1_AMT + CALCULATED_2_AMT + CALCULATED_3_AMT + CALCULATED_4_AMT + CALCULATED_5_AMT
                + CALCULATED_6_AMT + CALCULATED_7_AMT + CALCULATED_8_AMT + CALCULATED_9_AMT + CALCULATED_10_AMT
                + CALCULATED_11_AMT + CALCULATED_12_AMT + CALCULATED_13_AMT + CALCULATED_14_AMT + CALCULATED_15_AMT, 2) CALCULATED_0_AMT
        FROM BAD_DEBT_CALCULATION
    ) S ON (T.OID = S.OID)
    WHEN MATCHED THEN UPDATE SET
        T.BD_0_AMT = S.CALCULATED_0_AMT
      , T.BD_1_AMT = S.CALCULATED_1_AMT, T.BD_2_AMT = S.CALCULATED_2_AMT, T.BD_3_AMT = S.CALCULATED_3_AMT
      , T.BD_4_AMT = S.CALCULATED_4_AMT, T.BD_5_AMT = S.CALCULATED_5_AMT, T.BD_6_AMT = S.CALCULATED_6_AMT
      , T.BD_7_AMT = S.CALCULATED_7_AMT, T.BD_8_AMT = S.CALCULATED_8_AMT, T.BD_9_AMT = S.CALCULATED_9_AMT
      , T.BD_10_AMT = S.CALCULATED_10_AMT, T.BD_11_AMT = S.CALCULATED_11_AMT, T.BD_12_AMT = S.CALCULATED_12_AMT
      , T.BD_13_AMT = S.CALCULATED_13_AMT, T.BD_14_AMT = S.CALCULATED_14_AMT, T.BD_15_AMT = S.CALCULATED_15_AMT
      , T.DATEUPD = SYSDATE
      , T.USERUPD = SESSION_USER;

    INSERT INTO ZTAB_CPM_LOG(
        CPM, STEP, EXECTIME, CREATEBY, COD_SCENARIO, COD_PERIODO, COD_AZIENDA
    ) VALUES (
        'CPM_SP_M2M_ARP_BD_M_PHASE2', 'STEP2 坏账计算完成', SYSDATE, SESSION_USER,
        V_SCENARIO, V_PERIODO, V_AZIENDA
    );
    COMMIT;
    -- ============================================================================
    -- STEP3：坏账分摊及本月坏账发生额
    -- ============================================================================
    MERGE INTO AW_MR9_ARPM02_000001 T
    USING (
      WITH
      -- 当前期间目标表行，仅保留STEP3实际使用字段并前置公司、期间过滤。
      BASE_DATA AS (
        SELECT A.OID, A.COD_AZIENDA, A.CUST_CODE, A.COD_CONTO, A.COD_DEST2
            , A.D_SALE_DEPT, A.COD_AZI_CTP, A.NATURE_L3_NAME
            , A.BD_0_AMT, A.BD_1_AMT, A.BD_2_AMT, A.BD_3_AMT, A.BD_4_AMT
            , A.BD_5_AMT, A.BD_6_AMT, A.BD_7_AMT, A.BD_8_AMT, A.BD_9_AMT
            , A.BD_10_AMT, A.BD_11_AMT, A.BD_12_AMT, A.BD_13_AMT, A.BD_14_AMT, A.BD_15_AMT
            , A.SPID_1_AMT, A.SPID_2_AMT, A.SPID_3_AMT, A.SPID_4_AMT, A.SPID_5_AMT
            , A.SPID_6_AMT, A.SPID_7_AMT, A.SPID_8_AMT, A.SPID_9_AMT, A.SPID_10_AMT
            , A.SPID_11_AMT, A.SPID_12_AMT, A.SPID_13_AMT, A.SPID_14_AMT, A.SPID_15_AMT
          FROM AW_MR9_ARPM02_000001 A
         WHERE A.COD_SCENARIO = V_SCENARIO
           AND A.COD_PERIODO = V_PERIODO
           AND A.COD_AZIENDA IN (
                 SELECT ELEM
                   FROM SESSION_AZIENDA_LIST
                  WHERE SESSION_ID = V_SESSION_ID
           )
      ),
      -- 个别认定仅用于判断存在性，先按完整科目粒度去重，避免逐行相关子查询。
      INDIVIDUAL_KEYS AS (
        SELECT I.COD_AZIENDA, I.CUST_CODE, I.COD_DEST2, I.COD_CONTO, I.NATURE_L3_NAME
          FROM AW_MR9_ARPM01_000001 I
         WHERE I.COD_SCENARIO = V_SCENARIO
           AND I.COD_PERIODO = V_PERIODO
           AND I.COD_CATEGORIA = 'ZFAMOUNT'
           AND I.D_ADJ_TYPE = 'ARP_02_002'
           AND I.COD_AZIENDA IN (
                 SELECT ELEM
                   FROM SESSION_AZIENDA_LIST
                  WHERE SESSION_ID = V_SESSION_ID
           )
         GROUP BY I.COD_AZIENDA, I.CUST_CODE, I.COD_DEST2, I.COD_CONTO, I.NATURE_L3_NAME
      ),
      -- 按公司、客商、科目一次汇总正数基数和负数各账龄金额，避免重复扫描。
      KEY_TOTAL AS (
        SELECT COD_AZIENDA, CUST_CODE, COD_CONTO
            , SUM(CASE WHEN BD_0_AMT > 0 THEN BD_0_AMT ELSE 0 END) POS_TOTAL
            , SUM(CASE WHEN BD_0_AMT < 0 THEN BD_1_AMT ELSE 0 END) AGE_ALLOC_1
            , SUM(CASE WHEN BD_0_AMT < 0 THEN BD_2_AMT ELSE 0 END) AGE_ALLOC_2
            , SUM(CASE WHEN BD_0_AMT < 0 THEN BD_3_AMT ELSE 0 END) AGE_ALLOC_3
            , SUM(CASE WHEN BD_0_AMT < 0 THEN BD_4_AMT ELSE 0 END) AGE_ALLOC_4
            , SUM(CASE WHEN BD_0_AMT < 0 THEN BD_5_AMT ELSE 0 END) AGE_ALLOC_5
            , SUM(CASE WHEN BD_0_AMT < 0 THEN BD_6_AMT ELSE 0 END) AGE_ALLOC_6
            , SUM(CASE WHEN BD_0_AMT < 0 THEN BD_7_AMT ELSE 0 END) AGE_ALLOC_7
            , SUM(CASE WHEN BD_0_AMT < 0 THEN BD_8_AMT ELSE 0 END) AGE_ALLOC_8
            , SUM(CASE WHEN BD_0_AMT < 0 THEN BD_9_AMT ELSE 0 END) AGE_ALLOC_9
            , SUM(CASE WHEN BD_0_AMT < 0 THEN BD_10_AMT ELSE 0 END) AGE_ALLOC_10
            , SUM(CASE WHEN BD_0_AMT < 0 THEN BD_11_AMT ELSE 0 END) AGE_ALLOC_11
            , SUM(CASE WHEN BD_0_AMT < 0 THEN BD_12_AMT ELSE 0 END) AGE_ALLOC_12
            , SUM(CASE WHEN BD_0_AMT < 0 THEN BD_13_AMT ELSE 0 END) AGE_ALLOC_13
            , SUM(CASE WHEN BD_0_AMT < 0 THEN BD_14_AMT ELSE 0 END) AGE_ALLOC_14
            , SUM(CASE WHEN BD_0_AMT < 0 THEN BD_15_AMT ELSE 0 END) AGE_ALLOC_15
          FROM BASE_DATA
         GROUP BY COD_AZIENDA, CUST_CODE, COD_CONTO
      ),
      -- 合并预聚合结果，源数据保持OID唯一且科目不跨组分摊。
      ALLOCATION_DATA AS (
        SELECT BASE_DATA.*
            , CASE WHEN INDIVIDUAL_KEYS.COD_AZIENDA IS NULL THEN 0 ELSE 1 END HAS_INDIVIDUAL
            , NVL(KEY_TOTAL.POS_TOTAL, 0) POS_TOTAL
            , CASE WHEN BASE_DATA.BD_0_AMT > 0 THEN BASE_DATA.BD_0_AMT / NULLIF(KEY_TOTAL.POS_TOTAL, 0) ELSE 0 END ALLOC_RATIO
            , NVL(KEY_TOTAL.AGE_ALLOC_1, 0) AGE_ALLOC_1, NVL(KEY_TOTAL.AGE_ALLOC_2, 0) AGE_ALLOC_2
            , NVL(KEY_TOTAL.AGE_ALLOC_3, 0) AGE_ALLOC_3, NVL(KEY_TOTAL.AGE_ALLOC_4, 0) AGE_ALLOC_4
            , NVL(KEY_TOTAL.AGE_ALLOC_5, 0) AGE_ALLOC_5, NVL(KEY_TOTAL.AGE_ALLOC_6, 0) AGE_ALLOC_6
            , NVL(KEY_TOTAL.AGE_ALLOC_7, 0) AGE_ALLOC_7, NVL(KEY_TOTAL.AGE_ALLOC_8, 0) AGE_ALLOC_8
            , NVL(KEY_TOTAL.AGE_ALLOC_9, 0) AGE_ALLOC_9, NVL(KEY_TOTAL.AGE_ALLOC_10, 0) AGE_ALLOC_10
            , NVL(KEY_TOTAL.AGE_ALLOC_11, 0) AGE_ALLOC_11, NVL(KEY_TOTAL.AGE_ALLOC_12, 0) AGE_ALLOC_12
            , NVL(KEY_TOTAL.AGE_ALLOC_13, 0) AGE_ALLOC_13, NVL(KEY_TOTAL.AGE_ALLOC_14, 0) AGE_ALLOC_14
            , NVL(KEY_TOTAL.AGE_ALLOC_15, 0) AGE_ALLOC_15
          FROM BASE_DATA
          LEFT JOIN INDIVIDUAL_KEYS
            ON INDIVIDUAL_KEYS.COD_AZIENDA = BASE_DATA.COD_AZIENDA
           AND INDIVIDUAL_KEYS.CUST_CODE = BASE_DATA.CUST_CODE
           AND INDIVIDUAL_KEYS.COD_DEST2 = BASE_DATA.COD_DEST2
           AND INDIVIDUAL_KEYS.COD_CONTO = BASE_DATA.COD_CONTO
           AND INDIVIDUAL_KEYS.NATURE_L3_NAME = BASE_DATA.NATURE_L3_NAME
          LEFT JOIN KEY_TOTAL
            ON KEY_TOTAL.COD_AZIENDA = BASE_DATA.COD_AZIENDA
           AND KEY_TOTAL.CUST_CODE = BASE_DATA.CUST_CODE
           AND KEY_TOTAL.COD_CONTO = BASE_DATA.COD_CONTO
      ),
      -- 汇总当前期间核销来源金额。
      WRITEOFF_DATA AS (
        SELECT COMPANY_CODE AS COD_AZIENDA
            , ACCT_MAP_CODE AS COD_CONTO
            , CUST_CODE
            , PROFITCENTER_CODE AS COD_DEST2
            , MARKETING_DEPT_CODE AS D_SALE_DEPT
            , SUM(BCY_0_AMT) AS WRITEOFF_AMT
          FROM DWD_FI_MR_ARAP_SUM_MI
        WHERE DT_MONTH = V_YEARMONTH
          AND ODS_SRC = 'WRITEOFF'
          AND COMPANY_CODE IN (
                SELECT ELEM
                  FROM SESSION_AZIENDA_LIST
                 WHERE SESSION_ID = V_SESSION_ID
          )
        GROUP BY COMPANY_CODE
                , ACCT_MAP_CODE
                , CUST_CODE
                , PROFITCENTER_CODE
                , MARKETING_DEPT_CODE
      ),
      -- 汇总上月同公司、客户和利润中心的期末坏账金额。
      LAST_MONTH_DATA AS (
        SELECT COD_AZIENDA, COD_CONTO, CUST_CODE, COD_DEST2, SUM(BD_AFAL_0_AMT) LM_BD_AFAL_0_AMT
          FROM AW_MR9_ARPM02_000001
        WHERE COD_SCENARIO = V_LM_SCENARIO
          AND COD_PERIODO = V_LM_PERIODO
          AND COD_AZIENDA IN (
                SELECT ELEM
                  FROM SESSION_AZIENDA_LIST
                 WHERE SESSION_ID = V_SESSION_ID
          )
        GROUP BY COD_AZIENDA, COD_CONTO, CUST_CODE, COD_DEST2
      ),
      -- 计算各账龄分摊金额、期末坏账金额及计提方式。
      CALCULATION_RESULT AS (
        SELECT ALLOCATION_DATA.OID
            , ALLOCATION_DATA.ALLOC_RATIO BD_ALLOC_RATIO
            , ALLOCATION_DATA.AGE_ALLOC_1 * ALLOCATION_DATA.ALLOC_RATIO AGE_ALLOC_1_AMT
            , ALLOCATION_DATA.AGE_ALLOC_2 * ALLOCATION_DATA.ALLOC_RATIO AGE_ALLOC_2_AMT
            , ALLOCATION_DATA.AGE_ALLOC_3 * ALLOCATION_DATA.ALLOC_RATIO AGE_ALLOC_3_AMT
            , ALLOCATION_DATA.AGE_ALLOC_4 * ALLOCATION_DATA.ALLOC_RATIO AGE_ALLOC_4_AMT
            , ALLOCATION_DATA.AGE_ALLOC_5 * ALLOCATION_DATA.ALLOC_RATIO AGE_ALLOC_5_AMT
            , ALLOCATION_DATA.AGE_ALLOC_6 * ALLOCATION_DATA.ALLOC_RATIO AGE_ALLOC_6_AMT
            , ALLOCATION_DATA.AGE_ALLOC_7 * ALLOCATION_DATA.ALLOC_RATIO AGE_ALLOC_7_AMT
            , ALLOCATION_DATA.AGE_ALLOC_8 * ALLOCATION_DATA.ALLOC_RATIO AGE_ALLOC_8_AMT
            , ALLOCATION_DATA.AGE_ALLOC_9 * ALLOCATION_DATA.ALLOC_RATIO AGE_ALLOC_9_AMT
            , ALLOCATION_DATA.AGE_ALLOC_10 * ALLOCATION_DATA.ALLOC_RATIO AGE_ALLOC_10_AMT
            , ALLOCATION_DATA.AGE_ALLOC_11 * ALLOCATION_DATA.ALLOC_RATIO AGE_ALLOC_11_AMT
            , ALLOCATION_DATA.AGE_ALLOC_12 * ALLOCATION_DATA.ALLOC_RATIO AGE_ALLOC_12_AMT
            , ALLOCATION_DATA.AGE_ALLOC_13 * ALLOCATION_DATA.ALLOC_RATIO AGE_ALLOC_13_AMT
            , ALLOCATION_DATA.AGE_ALLOC_14 * ALLOCATION_DATA.ALLOC_RATIO AGE_ALLOC_14_AMT
            , ALLOCATION_DATA.AGE_ALLOC_15 * ALLOCATION_DATA.ALLOC_RATIO AGE_ALLOC_15_AMT
            , CASE WHEN ALLOCATION_DATA.HAS_INDIVIDUAL = 1 THEN ALLOCATION_DATA.SPID_1_AMT
                    WHEN ALLOCATION_DATA.BD_0_AMT > 0 THEN ALLOCATION_DATA.BD_1_AMT + ALLOCATION_DATA.AGE_ALLOC_1 * ALLOCATION_DATA.ALLOC_RATIO
                    ELSE 0 END BD_AFAL_1_AMT
            , CASE WHEN ALLOCATION_DATA.HAS_INDIVIDUAL = 1 THEN ALLOCATION_DATA.SPID_2_AMT
                    WHEN ALLOCATION_DATA.BD_0_AMT > 0 THEN ALLOCATION_DATA.BD_2_AMT + ALLOCATION_DATA.AGE_ALLOC_2 * ALLOCATION_DATA.ALLOC_RATIO
                    ELSE 0 END BD_AFAL_2_AMT
            , CASE WHEN ALLOCATION_DATA.HAS_INDIVIDUAL = 1 THEN ALLOCATION_DATA.SPID_3_AMT
                    WHEN ALLOCATION_DATA.BD_0_AMT > 0 THEN ALLOCATION_DATA.BD_3_AMT + ALLOCATION_DATA.AGE_ALLOC_3 * ALLOCATION_DATA.ALLOC_RATIO
                    ELSE 0 END BD_AFAL_3_AMT
            , CASE WHEN ALLOCATION_DATA.HAS_INDIVIDUAL = 1 THEN ALLOCATION_DATA.SPID_4_AMT
                    WHEN ALLOCATION_DATA.BD_0_AMT > 0 THEN ALLOCATION_DATA.BD_4_AMT + ALLOCATION_DATA.AGE_ALLOC_4 * ALLOCATION_DATA.ALLOC_RATIO
                    ELSE 0 END BD_AFAL_4_AMT
            , CASE WHEN ALLOCATION_DATA.HAS_INDIVIDUAL = 1 THEN ALLOCATION_DATA.SPID_5_AMT
                    WHEN ALLOCATION_DATA.BD_0_AMT > 0 THEN ALLOCATION_DATA.BD_5_AMT + ALLOCATION_DATA.AGE_ALLOC_5 * ALLOCATION_DATA.ALLOC_RATIO
                    ELSE 0 END BD_AFAL_5_AMT
            , CASE WHEN ALLOCATION_DATA.HAS_INDIVIDUAL = 1 THEN ALLOCATION_DATA.SPID_6_AMT
                    WHEN ALLOCATION_DATA.BD_0_AMT > 0 THEN ALLOCATION_DATA.BD_6_AMT + ALLOCATION_DATA.AGE_ALLOC_6 * ALLOCATION_DATA.ALLOC_RATIO
                    ELSE 0 END BD_AFAL_6_AMT
            , CASE WHEN ALLOCATION_DATA.HAS_INDIVIDUAL = 1 THEN ALLOCATION_DATA.SPID_7_AMT
                    WHEN ALLOCATION_DATA.BD_0_AMT > 0 THEN ALLOCATION_DATA.BD_7_AMT + ALLOCATION_DATA.AGE_ALLOC_7 * ALLOCATION_DATA.ALLOC_RATIO
                    ELSE 0 END BD_AFAL_7_AMT
            , CASE WHEN ALLOCATION_DATA.HAS_INDIVIDUAL = 1 THEN ALLOCATION_DATA.SPID_8_AMT
                    WHEN ALLOCATION_DATA.BD_0_AMT > 0 THEN ALLOCATION_DATA.BD_8_AMT + ALLOCATION_DATA.AGE_ALLOC_8 * ALLOCATION_DATA.ALLOC_RATIO
                    ELSE 0 END BD_AFAL_8_AMT
            , CASE WHEN ALLOCATION_DATA.HAS_INDIVIDUAL = 1 THEN ALLOCATION_DATA.SPID_9_AMT
                    WHEN ALLOCATION_DATA.BD_0_AMT > 0 THEN ALLOCATION_DATA.BD_9_AMT + ALLOCATION_DATA.AGE_ALLOC_9 * ALLOCATION_DATA.ALLOC_RATIO
                    ELSE 0 END BD_AFAL_9_AMT
            , CASE WHEN ALLOCATION_DATA.HAS_INDIVIDUAL = 1 THEN ALLOCATION_DATA.SPID_10_AMT
                    WHEN ALLOCATION_DATA.BD_0_AMT > 0 THEN ALLOCATION_DATA.BD_10_AMT + ALLOCATION_DATA.AGE_ALLOC_10 * ALLOCATION_DATA.ALLOC_RATIO
                    ELSE 0 END BD_AFAL_10_AMT
            , CASE WHEN ALLOCATION_DATA.HAS_INDIVIDUAL = 1 THEN ALLOCATION_DATA.SPID_11_AMT
                    WHEN ALLOCATION_DATA.BD_0_AMT > 0 THEN ALLOCATION_DATA.BD_11_AMT + ALLOCATION_DATA.AGE_ALLOC_11 * ALLOCATION_DATA.ALLOC_RATIO
                    ELSE 0 END BD_AFAL_11_AMT
            , CASE WHEN ALLOCATION_DATA.HAS_INDIVIDUAL = 1 THEN ALLOCATION_DATA.SPID_12_AMT
                    WHEN ALLOCATION_DATA.BD_0_AMT > 0 THEN ALLOCATION_DATA.BD_12_AMT + ALLOCATION_DATA.AGE_ALLOC_12 * ALLOCATION_DATA.ALLOC_RATIO
                    ELSE 0 END BD_AFAL_12_AMT
            , CASE WHEN ALLOCATION_DATA.HAS_INDIVIDUAL = 1 THEN ALLOCATION_DATA.SPID_13_AMT
                    WHEN ALLOCATION_DATA.BD_0_AMT > 0 THEN ALLOCATION_DATA.BD_13_AMT + ALLOCATION_DATA.AGE_ALLOC_13 * ALLOCATION_DATA.ALLOC_RATIO
                    ELSE 0 END BD_AFAL_13_AMT
            , CASE WHEN ALLOCATION_DATA.HAS_INDIVIDUAL = 1 THEN ALLOCATION_DATA.SPID_14_AMT
                    WHEN ALLOCATION_DATA.BD_0_AMT > 0 THEN ALLOCATION_DATA.BD_14_AMT + ALLOCATION_DATA.AGE_ALLOC_14 * ALLOCATION_DATA.ALLOC_RATIO
                    ELSE 0 END BD_AFAL_14_AMT
            , CASE WHEN ALLOCATION_DATA.HAS_INDIVIDUAL = 1 THEN ALLOCATION_DATA.SPID_15_AMT
                    WHEN ALLOCATION_DATA.BD_0_AMT > 0 THEN ALLOCATION_DATA.BD_15_AMT + ALLOCATION_DATA.AGE_ALLOC_15 * ALLOCATION_DATA.ALLOC_RATIO
                    ELSE 0 END BD_AFAL_15_AMT
            , NVL(LAST_MONTH_DATA.LM_BD_AFAL_0_AMT, 0) LM_BD_AFAL_0_AMT
            , NVL(WRITEOFF_DATA.WRITEOFF_AMT, 0) WRITEOFF_AMT
            , CASE WHEN ALLOCATION_DATA.HAS_INDIVIDUAL = 1 THEN '按单项计提'
                    WHEN ALLOCATION_DATA.COD_AZIENDA IN (
                          SELECT ELEM
                            FROM SESSION_V_REF_AZIENDA
                            WHERE SESSION_ID = V_SESSION_ID
                              AND HIE = '01'
                              AND NODE = '2910'
                        ) THEN
                        CASE WHEN ALLOCATION_DATA.COD_AZI_CTP IN (
                                    SELECT ELEM
                                      FROM SESSION_V_REF_AZIENDA
                                    WHERE SESSION_ID = V_SESSION_ID
                                      AND HIE = '01'
                                      AND NODE = '2000B'
                              ) THEN '视像合并组合'
                              WHEN ALLOCATION_DATA.COD_AZI_CTP IN (
                                    SELECT ELEM
                                      FROM SESSION_V_REF_AZIENDA
                                    WHERE SESSION_ID = V_SESSION_ID
                                      AND HIE = '01'
                                      AND NODE = '1000'
                              ) THEN '关联方组合'
                              ELSE 'TVS组合' END
                    WHEN ALLOCATION_DATA.COD_AZIENDA IN (
                          SELECT ELEM
                            FROM SESSION_V_REF_AZIENDA
                            WHERE SESSION_ID = V_SESSION_ID
                              AND HIE = '01'
                              AND NODE = '2000'
                        ) THEN
                        CASE WHEN ALLOCATION_DATA.COD_AZI_CTP IN (
                                    SELECT ELEM
                                      FROM SESSION_V_REF_AZIENDA
                                    WHERE SESSION_ID = V_SESSION_ID
                                      AND HIE = '01'
                                      AND NODE = '2000B'
                              ) THEN '视像合并组合'
                              WHEN ALLOCATION_DATA.COD_AZI_CTP IN (
                                    SELECT ELEM
                                      FROM SESSION_V_REF_AZIENDA
                                    WHERE SESSION_ID = V_SESSION_ID
                                      AND HIE = '01'
                                      AND NODE = '1000'
                              ) THEN '关联方组合'
                              ELSE '账龄组合' END
              END BD_PROV_METHOD
          FROM ALLOCATION_DATA
          LEFT JOIN LAST_MONTH_DATA
            ON LAST_MONTH_DATA.COD_AZIENDA = ALLOCATION_DATA.COD_AZIENDA
          AND LAST_MONTH_DATA.COD_CONTO = ALLOCATION_DATA.COD_CONTO
          AND LAST_MONTH_DATA.CUST_CODE = ALLOCATION_DATA.CUST_CODE
          AND LAST_MONTH_DATA.COD_DEST2 = ALLOCATION_DATA.COD_DEST2
          LEFT JOIN WRITEOFF_DATA
            ON WRITEOFF_DATA.COD_AZIENDA = ALLOCATION_DATA.COD_AZIENDA
          AND WRITEOFF_DATA.COD_CONTO = ALLOCATION_DATA.COD_CONTO
          AND WRITEOFF_DATA.CUST_CODE = ALLOCATION_DATA.CUST_CODE
          AND WRITEOFF_DATA.COD_DEST2 = ALLOCATION_DATA.COD_DEST2
          AND WRITEOFF_DATA.D_SALE_DEPT = ALLOCATION_DATA.D_SALE_DEPT
      )
      -- 在外层统一计算合计字段，UPDATE 仅负责回写结果。
      SELECT CALCULATION_RESULT.OID
          , CALCULATION_RESULT.BD_ALLOC_RATIO
          , CALCULATION_RESULT.AGE_ALLOC_1_AMT
          + CALCULATION_RESULT.AGE_ALLOC_2_AMT
          + CALCULATION_RESULT.AGE_ALLOC_3_AMT
          + CALCULATION_RESULT.AGE_ALLOC_4_AMT
          + CALCULATION_RESULT.AGE_ALLOC_5_AMT
          + CALCULATION_RESULT.AGE_ALLOC_6_AMT
          + CALCULATION_RESULT.AGE_ALLOC_7_AMT
          + CALCULATION_RESULT.AGE_ALLOC_8_AMT
          + CALCULATION_RESULT.AGE_ALLOC_9_AMT
          + CALCULATION_RESULT.AGE_ALLOC_10_AMT
          + CALCULATION_RESULT.AGE_ALLOC_11_AMT
          + CALCULATION_RESULT.AGE_ALLOC_12_AMT
          + CALCULATION_RESULT.AGE_ALLOC_13_AMT
          + CALCULATION_RESULT.AGE_ALLOC_14_AMT
          + CALCULATION_RESULT.AGE_ALLOC_15_AMT AGE_ALLOC_0_AMT
          , CALCULATION_RESULT.AGE_ALLOC_1_AMT
          , CALCULATION_RESULT.AGE_ALLOC_2_AMT
          , CALCULATION_RESULT.AGE_ALLOC_3_AMT
          , CALCULATION_RESULT.AGE_ALLOC_4_AMT
          , CALCULATION_RESULT.AGE_ALLOC_5_AMT
          , CALCULATION_RESULT.AGE_ALLOC_6_AMT
          , CALCULATION_RESULT.AGE_ALLOC_7_AMT
          , CALCULATION_RESULT.AGE_ALLOC_8_AMT
          , CALCULATION_RESULT.AGE_ALLOC_9_AMT
          , CALCULATION_RESULT.AGE_ALLOC_10_AMT
          , CALCULATION_RESULT.AGE_ALLOC_11_AMT
          , CALCULATION_RESULT.AGE_ALLOC_12_AMT
          , CALCULATION_RESULT.AGE_ALLOC_13_AMT
          , CALCULATION_RESULT.AGE_ALLOC_14_AMT
          , CALCULATION_RESULT.AGE_ALLOC_15_AMT
          , CALCULATION_RESULT.BD_AFAL_1_AMT
          , CALCULATION_RESULT.BD_AFAL_2_AMT
          , CALCULATION_RESULT.BD_AFAL_3_AMT
          , CALCULATION_RESULT.BD_AFAL_4_AMT
          , CALCULATION_RESULT.BD_AFAL_5_AMT
          , CALCULATION_RESULT.BD_AFAL_6_AMT
          , CALCULATION_RESULT.BD_AFAL_7_AMT
          , CALCULATION_RESULT.BD_AFAL_8_AMT
          , CALCULATION_RESULT.BD_AFAL_9_AMT
          , CALCULATION_RESULT.BD_AFAL_10_AMT
          , CALCULATION_RESULT.BD_AFAL_11_AMT
          , CALCULATION_RESULT.BD_AFAL_12_AMT
          , CALCULATION_RESULT.BD_AFAL_13_AMT
          , CALCULATION_RESULT.BD_AFAL_14_AMT
          , CALCULATION_RESULT.BD_AFAL_15_AMT
          , CALCULATION_RESULT.BD_AFAL_1_AMT
          + CALCULATION_RESULT.BD_AFAL_2_AMT
          + CALCULATION_RESULT.BD_AFAL_3_AMT
          + CALCULATION_RESULT.BD_AFAL_4_AMT
          + CALCULATION_RESULT.BD_AFAL_5_AMT
          + CALCULATION_RESULT.BD_AFAL_6_AMT
          + CALCULATION_RESULT.BD_AFAL_7_AMT
          + CALCULATION_RESULT.BD_AFAL_8_AMT
          + CALCULATION_RESULT.BD_AFAL_9_AMT
          + CALCULATION_RESULT.BD_AFAL_10_AMT
          + CALCULATION_RESULT.BD_AFAL_11_AMT
          + CALCULATION_RESULT.BD_AFAL_12_AMT
          + CALCULATION_RESULT.BD_AFAL_13_AMT
          + CALCULATION_RESULT.BD_AFAL_14_AMT
          + CALCULATION_RESULT.BD_AFAL_15_AMT BD_AFAL_0_AMT
          , CALCULATION_RESULT.LM_BD_AFAL_0_AMT
          , CALCULATION_RESULT.BD_PROV_METHOD
          , CALCULATION_RESULT.WRITEOFF_AMT
          , (CALCULATION_RESULT.BD_AFAL_1_AMT
            + CALCULATION_RESULT.BD_AFAL_2_AMT
            + CALCULATION_RESULT.BD_AFAL_3_AMT
            + CALCULATION_RESULT.BD_AFAL_4_AMT
            + CALCULATION_RESULT.BD_AFAL_5_AMT
            + CALCULATION_RESULT.BD_AFAL_6_AMT
            + CALCULATION_RESULT.BD_AFAL_7_AMT
            + CALCULATION_RESULT.BD_AFAL_8_AMT
            + CALCULATION_RESULT.BD_AFAL_9_AMT
            + CALCULATION_RESULT.BD_AFAL_10_AMT
            + CALCULATION_RESULT.BD_AFAL_11_AMT
            + CALCULATION_RESULT.BD_AFAL_12_AMT
            + CALCULATION_RESULT.BD_AFAL_13_AMT
            + CALCULATION_RESULT.BD_AFAL_14_AMT
            + CALCULATION_RESULT.BD_AFAL_15_AMT)
            - CALCULATION_RESULT.LM_BD_AFAL_0_AMT
            + CALCULATION_RESULT.WRITEOFF_AMT MTD_BD_PROV_OCUR_AMT
          , SYSDATE DATEUPD
          , SESSION_USER USERUPD
        FROM CALCULATION_RESULT
    ) S ON (T.OID = S.OID)
    WHEN MATCHED THEN UPDATE SET
        T.BD_ALLOC_RATIO = S.BD_ALLOC_RATIO
      , T.AGE_ALLOC_0_AMT = S.AGE_ALLOC_0_AMT
      , T.AGE_ALLOC_1_AMT = S.AGE_ALLOC_1_AMT
      , T.AGE_ALLOC_2_AMT = S.AGE_ALLOC_2_AMT
      , T.AGE_ALLOC_3_AMT = S.AGE_ALLOC_3_AMT
      , T.AGE_ALLOC_4_AMT = S.AGE_ALLOC_4_AMT
      , T.AGE_ALLOC_5_AMT = S.AGE_ALLOC_5_AMT
      , T.AGE_ALLOC_6_AMT = S.AGE_ALLOC_6_AMT
      , T.AGE_ALLOC_7_AMT = S.AGE_ALLOC_7_AMT
      , T.AGE_ALLOC_8_AMT = S.AGE_ALLOC_8_AMT
      , T.AGE_ALLOC_9_AMT = S.AGE_ALLOC_9_AMT
      , T.AGE_ALLOC_10_AMT = S.AGE_ALLOC_10_AMT
      , T.AGE_ALLOC_11_AMT = S.AGE_ALLOC_11_AMT
      , T.AGE_ALLOC_12_AMT = S.AGE_ALLOC_12_AMT
      , T.AGE_ALLOC_13_AMT = S.AGE_ALLOC_13_AMT
      , T.AGE_ALLOC_14_AMT = S.AGE_ALLOC_14_AMT
      , T.AGE_ALLOC_15_AMT = S.AGE_ALLOC_15_AMT
      , T.BD_AFAL_0_AMT = S.BD_AFAL_0_AMT
      , T.BD_AFAL_1_AMT = S.BD_AFAL_1_AMT
      , T.BD_AFAL_2_AMT = S.BD_AFAL_2_AMT
      , T.BD_AFAL_3_AMT = S.BD_AFAL_3_AMT
      , T.BD_AFAL_4_AMT = S.BD_AFAL_4_AMT
      , T.BD_AFAL_5_AMT = S.BD_AFAL_5_AMT
      , T.BD_AFAL_6_AMT = S.BD_AFAL_6_AMT
      , T.BD_AFAL_7_AMT = S.BD_AFAL_7_AMT
      , T.BD_AFAL_8_AMT = S.BD_AFAL_8_AMT
      , T.BD_AFAL_9_AMT = S.BD_AFAL_9_AMT
      , T.BD_AFAL_10_AMT = S.BD_AFAL_10_AMT
      , T.BD_AFAL_11_AMT = S.BD_AFAL_11_AMT
      , T.BD_AFAL_12_AMT = S.BD_AFAL_12_AMT
      , T.BD_AFAL_13_AMT = S.BD_AFAL_13_AMT
      , T.BD_AFAL_14_AMT = S.BD_AFAL_14_AMT
      , T.BD_AFAL_15_AMT = S.BD_AFAL_15_AMT
      , T.LM_BD_AFAL_0_AMT = S.LM_BD_AFAL_0_AMT
      , T.BD_PROV_METHOD = S.BD_PROV_METHOD
      , T.WRITEOFF_AMT = S.WRITEOFF_AMT
      , T.MTD_BD_PROV_OCUR_AMT = S.MTD_BD_PROV_OCUR_AMT
      , T.DATEUPD = S.DATEUPD
      , T.USERUPD = S.USERUPD;

    INSERT INTO ZTAB_CPM_LOG(
        CPM, STEP, EXECTIME, CREATEBY, COD_SCENARIO, COD_PERIODO, COD_AZIENDA
    ) VALUES (
        'CPM_SP_M2M_ARP_BD_M_PHASE2', 'STEP3 坏账分摊及本月坏账发生额完成', SYSDATE, SESSION_USER,
        V_SCENARIO, V_PERIODO, V_AZIENDA
    );
    COMMIT;
    -- 清理当前会话数据，并在成功路径最后统一提交。
    DELETE FROM SESSION_AZIENDA_LIST
    WHERE SESSION_ID = V_SESSION_ID;
    DELETE FROM SESSION_V_REF_AZIENDA
    WHERE SESSION_ID = V_SESSION_ID;

    INSERT INTO ZTAB_CPM_LOG(
        CPM, STEP, EXECTIME, CREATEBY, COD_SCENARIO, COD_PERIODO, COD_AZIENDA
    ) VALUES (
        'CPM_SP_M2M_ARP_BD_M_PHASE2', 'END 执行完成', SYSDATE, SESSION_USER,
        V_SCENARIO, V_PERIODO, V_AZIENDA
    );
    COMMIT;
  EXCEPTION
    WHEN OTHERS THEN
      V_ERROR_COD := SQLCODE;
      V_ERROR_MSG := SUBSTR(SQLERRM, 1, 4000);
      INSERT INTO ZTAB_CPM_LOG(
          CPM, STEP, REMARK, EXECTIME, CREATEBY, COD_SCENARIO, COD_PERIODO, COD_AZIENDA
      ) VALUES (
          'CPM_SP_M2M_ARP_BD_M_PHASE2', 'ERROR 执行报错',
          V_ERROR_COD || ':' || V_ERROR_MSG, SYSDATE, SESSION_USER,
          V_SCENARIO, V_PERIODO, NVL(V_AZIENDA, P_AZIENDA)
      );
      COMMIT;
      RAISE;
  END CPM_SP_M2M_ARP_BD_M_PHASE2;
