-- 往来账龄汇总表（Oracle）
-- 目标表：DWD_FI_MR_ARAP_SUM_MI
-- 表类型：汇总事实表；数据分层：DWD

CREATE TABLE DWD_FI_MR_ARAP_SUM_MI (
      DT_MONTH VARCHAR2(6)
    , YEAR VARCHAR2(4)
    , MONTH VARCHAR2(2)
    , COMPANY_CODE VARCHAR2(8)
    , CUST_CODE VARCHAR2(30)
    , CUST_NAME VARCHAR2(200)
    , CUST_HEAD_CODE VARCHAR2(30)
    , CUST_HEAD_NAME VARCHAR2(200)
    , CUST_BRANCH_CODE VARCHAR2(20)
    , CUST_BRANCH_NAME VARCHAR2(200)
    , CP_COMPANY_CODE VARCHAR2(30)
    , COUNTRY_CODE VARCHAR2(8)
    , COUNTRY_NAME VARCHAR2(200)
    , ACCT_TYPE_CODE VARCHAR2(20)
    , ACCT_SRC_CODE VARCHAR2(30)
    , ACCT_MAP_CODE VARCHAR2(30)
    , CHANNEL_L1_CODE VARCHAR2(30)
    , CHANNEL_L1_NAME VARCHAR2(200)
    , CHANNEL_L2_CODE VARCHAR2(30)
    , CHANNEL_L2_NAME VARCHAR2(200)
    , CHANNEL_L3_CODE VARCHAR2(30)
    , CHANNEL_L3_NAME VARCHAR2(200)
    , ONOFFLINE_CODE VARCHAR2(30)
    , ONOFFLINE_NAME VARCHAR2(200)
    , SRC_PROFITCENTER_CODE VARCHAR2(30)
    , SRC_PROFITCENTER_NAME VARCHAR2(200)
    , PROFITCENTER_CODE VARCHAR2(30)
    , PROFITCENTER_NAME VARCHAR2(200)
    , BUS_RANGE_CODE VARCHAR2(30)
    , BUS_RANGE_NAME VARCHAR2(200)
    , MARKETING_DEPT_CODE VARCHAR2(30)
    , MARKETING_DEPT_NAME VARCHAR2(200)
    , PAY_REASON_CODE VARCHAR2(20)
    , BCY_CODE VARCHAR2(5)
    , QCY_CODE VARCHAR2(200)
    , BCY_0_AMT NUMBER(27, 9)
    , BCY_1_AMT NUMBER(27, 9)
    , BCY_2_AMT NUMBER(27, 9)
    , BCY_3_AMT NUMBER(27, 9)
    , BCY_4_AMT NUMBER(27, 9)
    , BCY_5_AMT NUMBER(27, 9)
    , BCY_6_AMT NUMBER(27, 9)
    , BCY_7_AMT NUMBER(27, 9)
    , BCY_8_AMT NUMBER(27, 9)
    , BCY_9_AMT NUMBER(27, 9)
    , BCY_10_AMT NUMBER(27, 9)
    , BCY_11_AMT NUMBER(27, 9)
    , BCY_12_AMT NUMBER(27, 9)
    , BCY_13_AMT NUMBER(27, 9)
    , BCY_14_AMT NUMBER(27, 9)
    , BCY_15_AMT NUMBER(27, 9)
    , QCY_0_AMT NUMBER(27, 9)
    , QCY_1_AMT NUMBER(27, 9)
    , QCY_2_AMT NUMBER(27, 9)
    , QCY_3_AMT NUMBER(27, 9)
    , QCY_4_AMT NUMBER(27, 9)
    , QCY_5_AMT NUMBER(27, 9)
    , QCY_6_AMT NUMBER(27, 9)
    , QCY_7_AMT NUMBER(27, 9)
    , QCY_8_AMT NUMBER(27, 9)
    , QCY_9_AMT NUMBER(27, 9)
    , QCY_10_AMT NUMBER(27, 9)
    , QCY_11_AMT NUMBER(27, 9)
    , QCY_12_AMT NUMBER(27, 9)
    , QCY_13_AMT NUMBER(27, 9)
    , QCY_14_AMT NUMBER(27, 9)
    , QCY_15_AMT NUMBER(27, 9)
    , PAYS_TRAN VARCHAR2(100)
    , SYSTEM_SRC VARCHAR2(150)
    , ODS_SRC VARCHAR2(200)
    , REB_TYPE VARCHAR2(50)
    , UFEE_UREB_FLAG VARCHAR2(30)
    , ECLS_FLAG VARCHAR2(30)
    , LEDGER_STATUS VARCHAR2(50)
    , ACCT_CERT_TYPE VARCHAR2(20)
    , TAX_RATE NUMBER(27, 9)
    , NATURE_L1_NAME VARCHAR2(100)
    , NATURE_L2_NAME VARCHAR2(100)
    , NATURE_L3_NAME VARCHAR2(100)
    , EXCHANGE_RATE_EVAL_FLAG VARCHAR2(200)
    , IS_APAR_FLAG VARCHAR2(30)
    , PAY_TERM_CODE VARCHAR2(24)
    , PAY_TERM_DESC VARCHAR2(300)
    , LOAD_DT DATE
);

COMMENT ON TABLE DWD_FI_MR_ARAP_SUM_MI IS '往来账龄汇总表';

COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.DT_MONTH IS '年月YYYYMM';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.YEAR IS '年份';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.MONTH IS '月份';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.COMPANY_CODE IS '组织';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.CUST_CODE IS '客商编码';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.CUST_NAME IS '客商名称';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.CUST_HEAD_CODE IS '主户编码';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.CUST_HEAD_NAME IS '主户名称';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.CUST_BRANCH_CODE IS '分户编码';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.CUST_BRANCH_NAME IS '分户名称';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.CP_COMPANY_CODE IS '对方公司';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.COUNTRY_CODE IS '国家编码';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.COUNTRY_NAME IS '国家名称';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.ACCT_TYPE_CODE IS '科目类型：D应收，K应付';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.ACCT_SRC_CODE IS '原始科目编码';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.ACCT_MAP_CODE IS '映射后科目编码';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.CHANNEL_L1_CODE IS '一级公司分类编码';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.CHANNEL_L1_NAME IS '一级公司分类名称';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.CHANNEL_L2_CODE IS '二级公司分类编码';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.CHANNEL_L2_NAME IS '二级公司分类名称';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.CHANNEL_L3_CODE IS '三级公司分类编码';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.CHANNEL_L3_NAME IS '三级公司分类名称';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.ONOFFLINE_CODE IS '渠道分组编码';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.ONOFFLINE_NAME IS '渠道分组名称';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.SRC_PROFITCENTER_CODE IS '原始利润中心编码';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.SRC_PROFITCENTER_NAME IS '原始利润中心名称';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.PROFITCENTER_CODE IS '映射后利润中心编码';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.PROFITCENTER_NAME IS '映射后利润中心名称';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.BUS_RANGE_CODE IS '业务范围编码';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.BUS_RANGE_NAME IS '业务范围名称';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.MARKETING_DEPT_CODE IS '业务管理单元编码';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.MARKETING_DEPT_NAME IS '业务管理单元名称';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.PAY_REASON_CODE IS '付款原因代码';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.BCY_CODE IS '本位币币种';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.QCY_CODE IS '交易币币种';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.BCY_0_AMT IS '本位币金额-总金额，等于BCY_1_AMT至BCY_15_AMT之和';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.BCY_1_AMT IS '本位币金额-账龄区间段1';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.BCY_2_AMT IS '本位币金额-账龄区间段2';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.BCY_3_AMT IS '本位币金额-账龄区间段3';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.BCY_4_AMT IS '本位币金额-账龄区间段4';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.BCY_5_AMT IS '本位币金额-账龄区间段5';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.BCY_6_AMT IS '本位币金额-账龄区间段6';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.BCY_7_AMT IS '本位币金额-账龄区间段7';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.BCY_8_AMT IS '本位币金额-账龄区间段8';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.BCY_9_AMT IS '本位币金额-账龄区间段9';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.BCY_10_AMT IS '本位币金额-账龄区间段10';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.BCY_11_AMT IS '本位币金额-账龄区间段11';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.BCY_12_AMT IS '本位币金额-账龄区间段12';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.BCY_13_AMT IS '本位币金额-账龄区间段13';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.BCY_14_AMT IS '本位币金额-账龄区间段14';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.BCY_15_AMT IS '本位币金额-账龄区间段15';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.QCY_0_AMT IS '交易币金额-总金额，等于QCY_1_AMT至QCY_15_AMT之和';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.QCY_1_AMT IS '交易币金额-账龄区间段1';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.QCY_2_AMT IS '交易币金额-账龄区间段2';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.QCY_3_AMT IS '交易币金额-账龄区间段3';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.QCY_4_AMT IS '交易币金额-账龄区间段4';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.QCY_5_AMT IS '交易币金额-账龄区间段5';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.QCY_6_AMT IS '交易币金额-账龄区间段6';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.QCY_7_AMT IS '交易币金额-账龄区间段7';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.QCY_8_AMT IS '交易币金额-账龄区间段8';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.QCY_9_AMT IS '交易币金额-账龄区间段9';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.QCY_10_AMT IS '交易币金额-账龄区间段10';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.QCY_11_AMT IS '交易币金额-账龄区间段11';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.QCY_12_AMT IS '交易币金额-账龄区间段12';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.QCY_13_AMT IS '交易币金额-账龄区间段13';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.QCY_14_AMT IS '交易币金额-账龄区间段14';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.QCY_15_AMT IS '交易币金额-账龄区间段15';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.PAYS_TRAN IS '付款服务商的付款编号';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.SYSTEM_SRC IS '来源系统';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.ODS_SRC IS '数据来源';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.REB_TYPE IS '返利性质';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.UFEE_UREB_FLAG IS '返利/费用标识';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.ECLS_FLAG IS '电商零售标识';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.LEDGER_STATUS IS '台账状态';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.ACCT_CERT_TYPE IS '凭证类型';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.TAX_RATE IS '税率';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.NATURE_L1_NAME IS '一级性质名称';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.NATURE_L2_NAME IS '二级性质名称';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.NATURE_L3_NAME IS '三级性质名称';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.EXCHANGE_RATE_EVAL_FLAG IS '汇率评估标识';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.IS_APAR_FLAG IS '账龄是否进数';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.PAY_TERM_CODE IS '付款条件代码';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.PAY_TERM_DESC IS '付款条件描述';
COMMENT ON COLUMN DWD_FI_MR_ARAP_SUM_MI.LOAD_DT IS '更新时间';
