-- 国际营销应收占用明细表（Oracle）
-- 目标表：DWD_FI_MR_AR_IMOCC_MI
-- 表类型：事实表；数据分层：DWD

CREATE TABLE DWD_FI_MR_AR_IMOCC_MI (
      DT_MONTH VARCHAR2(6)
    , YEAR VARCHAR2(4)
    , MONTH VARCHAR2(2)
    , COMPANY_SRC_CODE VARCHAR2(50)
    , COMPANY_CODE VARCHAR2(8)
    , REGION_CODE VARCHAR2(30)
    , REGION_NAME VARCHAR2(200)
    , REGION_FLAG VARCHAR2(30)
    , AREA_GROUP_CODE VARCHAR2(30)
    , AREA_GROUP_NAME VARCHAR2(200)
    , AREA_GROUP_FLAG VARCHAR2(200)
    , BUS_MODEL_CODE VARCHAR2(30)
    , PRODUCT_BIG_CLASS_CODE VARCHAR2(30)
    , PRODUCT_BIG_CLASS_NAME VARCHAR2(200)
    , PRODUCT_LINE_CODE VARCHAR2(30)
    , PRODUCT_LINE_NAME VARCHAR2(200)
    , CUST_PAY_TERM VARCHAR2(200)
    , DATA_SCOPE_CODE VARCHAR2(30)
    , CUST_CODE VARCHAR2(30)
    , CUST_NAME VARCHAR2(200)
    , CUST_BRANCH_CODE VARCHAR2(20)
    , CUST_BRANCH_NAME VARCHAR2(200)
    , CP_COMPANY_CODE VARCHAR2(30)
    , COUNTRY_CODE VARCHAR2(8)
    , COUNTRY_NAME VARCHAR2(200)
    , CHANNEL_L1_CODE VARCHAR2(30)
    , CHANNEL_L1_NAME VARCHAR2(200)
    , CHANNEL_L2_CODE VARCHAR2(30)
    , CHANNEL_L2_NAME VARCHAR2(200)
    , CHANNEL_L3_CODE VARCHAR2(30)
    , CHANNEL_L3_NAME VARCHAR2(200)
    , BUS_RANGE_CODE VARCHAR2(30)
    , BUS_RANGE_NAME VARCHAR2(200)
    , PROFITCENTER_CODE VARCHAR2(30)
    , PROFITCENTER_NAME VARCHAR2(200)
    , BCY_CODE VARCHAR2(5)
    , QCY_CODE VARCHAR2(5)
    , IMOCC_CNY_AMT NUMBER(27, 9)
    , IMOCC_CON_AMT NUMBER(27, 9)
    , IMOCC_USD_AMT NUMBER(27, 9)
    , ODS_SRC VARCHAR2(200)
    , LOAD_DT DATE
);

COMMENT ON TABLE DWD_FI_MR_AR_IMOCC_MI IS '国际营销应收占用明细表';

COMMENT ON COLUMN DWD_FI_MR_AR_IMOCC_MI.DT_MONTH IS '年月YYYYMM';
COMMENT ON COLUMN DWD_FI_MR_AR_IMOCC_MI.YEAR IS '年份';
COMMENT ON COLUMN DWD_FI_MR_AR_IMOCC_MI.MONTH IS '月份';
COMMENT ON COLUMN DWD_FI_MR_AR_IMOCC_MI.COMPANY_SRC_CODE IS '组织';
COMMENT ON COLUMN DWD_FI_MR_AR_IMOCC_MI.COMPANY_CODE IS '组织';
COMMENT ON COLUMN DWD_FI_MR_AR_IMOCC_MI.REGION_CODE IS '大区编码';
COMMENT ON COLUMN DWD_FI_MR_AR_IMOCC_MI.REGION_NAME IS '大区名称';
COMMENT ON COLUMN DWD_FI_MR_AR_IMOCC_MI.REGION_FLAG IS '大区标识';
COMMENT ON COLUMN DWD_FI_MR_AR_IMOCC_MI.AREA_GROUP_CODE IS '区组编码';
COMMENT ON COLUMN DWD_FI_MR_AR_IMOCC_MI.AREA_GROUP_NAME IS '区组名称';
COMMENT ON COLUMN DWD_FI_MR_AR_IMOCC_MI.AREA_GROUP_FLAG IS '区组标识';
COMMENT ON COLUMN DWD_FI_MR_AR_IMOCC_MI.BUS_MODEL_CODE IS '业务模式';
COMMENT ON COLUMN DWD_FI_MR_AR_IMOCC_MI.PRODUCT_BIG_CLASS_CODE IS '产品大类编码';
COMMENT ON COLUMN DWD_FI_MR_AR_IMOCC_MI.PRODUCT_BIG_CLASS_NAME IS '产品大类名称';
COMMENT ON COLUMN DWD_FI_MR_AR_IMOCC_MI.PRODUCT_LINE_CODE IS '产品线编码';
COMMENT ON COLUMN DWD_FI_MR_AR_IMOCC_MI.PRODUCT_LINE_NAME IS '产品线名称';
COMMENT ON COLUMN DWD_FI_MR_AR_IMOCC_MI.CUST_PAY_TERM IS '客户账期编码/描述';
COMMENT ON COLUMN DWD_FI_MR_AR_IMOCC_MI.DATA_SCOPE_CODE IS '范围';
COMMENT ON COLUMN DWD_FI_MR_AR_IMOCC_MI.CUST_CODE IS '客商编码';
COMMENT ON COLUMN DWD_FI_MR_AR_IMOCC_MI.CUST_NAME IS '客商名称';
COMMENT ON COLUMN DWD_FI_MR_AR_IMOCC_MI.CUST_BRANCH_CODE IS '分户编码';
COMMENT ON COLUMN DWD_FI_MR_AR_IMOCC_MI.CUST_BRANCH_NAME IS '分户名称';
COMMENT ON COLUMN DWD_FI_MR_AR_IMOCC_MI.CP_COMPANY_CODE IS '对方公司';
COMMENT ON COLUMN DWD_FI_MR_AR_IMOCC_MI.COUNTRY_CODE IS '国家编码';
COMMENT ON COLUMN DWD_FI_MR_AR_IMOCC_MI.COUNTRY_NAME IS '国家名称';
COMMENT ON COLUMN DWD_FI_MR_AR_IMOCC_MI.CHANNEL_L1_CODE IS '一级公司分类编码';
COMMENT ON COLUMN DWD_FI_MR_AR_IMOCC_MI.CHANNEL_L1_NAME IS '一级公司分类名称';
COMMENT ON COLUMN DWD_FI_MR_AR_IMOCC_MI.CHANNEL_L2_CODE IS '二级公司分类编码';
COMMENT ON COLUMN DWD_FI_MR_AR_IMOCC_MI.CHANNEL_L2_NAME IS '二级公司分类名称';
COMMENT ON COLUMN DWD_FI_MR_AR_IMOCC_MI.CHANNEL_L3_CODE IS '三级公司分类编码';
COMMENT ON COLUMN DWD_FI_MR_AR_IMOCC_MI.CHANNEL_L3_NAME IS '三级公司分类名称';
COMMENT ON COLUMN DWD_FI_MR_AR_IMOCC_MI.BUS_RANGE_CODE IS '业务范围编码';
COMMENT ON COLUMN DWD_FI_MR_AR_IMOCC_MI.BUS_RANGE_NAME IS '业务范围名称';
COMMENT ON COLUMN DWD_FI_MR_AR_IMOCC_MI.PROFITCENTER_CODE IS '利润中心编码';
COMMENT ON COLUMN DWD_FI_MR_AR_IMOCC_MI.PROFITCENTER_NAME IS '利润中心名称';
COMMENT ON COLUMN DWD_FI_MR_AR_IMOCC_MI.BCY_CODE IS '本位币币种';
COMMENT ON COLUMN DWD_FI_MR_AR_IMOCC_MI.QCY_CODE IS '交易币币种';
COMMENT ON COLUMN DWD_FI_MR_AR_IMOCC_MI.IMOCC_CNY_AMT IS '国际营销应收占用金额-人民币';
COMMENT ON COLUMN DWD_FI_MR_AR_IMOCC_MI.IMOCC_CON_AMT IS '国际营销应收占用金额-美元';
COMMENT ON COLUMN DWD_FI_MR_AR_IMOCC_MI.IMOCC_USD_AMT IS '国际营销应收占用金额-本位币';
COMMENT ON COLUMN DWD_FI_MR_AR_IMOCC_MI.ODS_SRC IS '数据来源';
COMMENT ON COLUMN DWD_FI_MR_AR_IMOCC_MI.LOAD_DT IS '更新时间';

GRANT ALL ON DWD_FI_MR_AR_IMOCC_MI TO app_read;
