CREATE OR REPLACE VIEW TGK_GB_HISENSE.V_APAR_ELEM_NODE_TAB AS
SELECT
/***************************************************
最后更新时间：20260407 09:48  更新人：XIAOYACHAO.EX
    目标系统：管报
      需求人：
        用途：用于往来账龄表集团子公司,内部,外部判断
        源表：AZIENDA_GERARCHIA
              AZIENDA_GERARCHIA_ABBI_TV
        赋权：GRANT SELECT ON V_APAR_ELEM_NODE_TAB TO tgk_gb_dev;
    特殊逻辑：
    版本信息：V1.初始版本创建 created by ZXZ at 20250605
 ALTER BY 20251230 XIAOYACHAO.EX 增加网科为外部
***************************************************/
 D1.COD_SCENARIO ,D1.COD_PERIODO,D1.ELEM, D1.NODE AS NODE,D2.NODE AS NODES
        ,CASE WHEN D1.COD_SCENARIO||D1.COD_PERIODO>='202506' AND D1.ELEM IN('1592','1088','4293','1800') THEN D1.HQ||'WB'
              WHEN D1.COD_SCENARIO||D1.COD_PERIODO>='202508' AND D1.ELEM LIKE '15%' THEN D1.HQ||'WB'  /*ALTER BY 20250828 XIAOYACHAO.EX 增加赛维公司为外部*/
              WHEN D1.COD_SCENARIO||D1.COD_PERIODO>='202510' AND D1.ELEM IN ('6430','6435','6898') THEN D1.HQ||'WB'   /*ALTER BY 20251027 XIAOYACHAO.EX 增加嘉科为外部*/
             /* WHEN D1.COD_SCENARIO||D1.COD_PERIODO>='202512' AND D1.NODE IN ('1600A') THEN D1.HQ||'WB'   \*ALTER BY 20251230 XIAOYACHAO.EX 增加网科为外部*\*/
              when D1.COD_SCENARIO||D1.COD_PERIODO>='202603' and d1.ELEM in ('1030','4100') then D1.HQ||'WB'  /*ALTER BY 20260402 XIAOYACAHO.EX 10130,4100 转为外部*/
              ELSE D1.HQ
          END AS HQ
  FROM (SELECT  COD_SCENARIO,COD_PERIODO,ELEM,
               CASE WHEN NODE = '4Z00' THEN '1009' ELSE  NODE END NODE,
               P.COD_AZIENDA_ELEGER_PADRE HQ
          FROM TGK_GB_HISENSE.V_REF_AZIENDA_TV TV,
               (SELECT A.COD_AZIENDA_ELEGER, COD_AZIENDA_ELEGER_PADRE
                  FROM TGK_GB_HISENSE.AZIENDA_GERARCHIA A
                 WHERE A.COD_AZIENDA_GERARCHIA_PADRE = '30'
                   AND A.COD_AZIENDA_ELEGER_PADRE IN ('1001', '1015')
                   AND COD_AZIENDA_ELEGER NOT IN ('8Z00')
                UNION
                SELECT '4Z00', '1001' FROM DUAL
              ) P
         WHERE TV.HIE = '30'
           AND TV.NODE = P.COD_AZIENDA_ELEGER
        UNION ALL
        SELECT  COD_SCENARIO,COD_PERIODO,COD_AZIENDA, 'NULL' || COD_AZIENDA, COD_AZIENDA_ELEGER HQ
          FROM TGK_GB_HISENSE.AZIENDA_GERARCHIA_ABBI_TV TV
         WHERE TV.COD_AZIENDA_GERARCHIA = '30'
           AND COD_AZIENDA_ELEGER IN ('1001', '1015')
         ) D1
  LEFT JOIN (SELECT COD_SCENARIO,COD_PERIODO,ELEM, NODE
               FROM TGK_GB_HISENSE.V_REF_AZIENDA_TV
              WHERE HIE = '30' AND NODE = '1730'
              ) D2
    ON D1.ELEM = D2.ELEM AND D1.COD_SCENARIO = D2.COD_SCENARIO AND D1.COD_PERIODO = D2.COD_PERIODO;