WITH AZI AS  /*公司 + 法定总部*/
(SELECT SEDE_LEGALE,MIN(COD_AZIENDA) AS COD_AZIENDA 
   FROM TGK_GB_HISENSE.AZIENDA
  WHERE SEDE_LEGALE IS NOT NULL GROUP BY SEDE_LEGALE
)
/*处理子区间格式*/
, XH AS (
SELECT ROW_NUMBER() OVER(PARTITION BY SUBSTR(BILL_CODE,1,INSTR(BILL_CODE,'-')-1)
                                      ,SUBSTR(BILL_CODE,INSTR(BILL_CODE,' ')+1)
                         ORDER BY SUBSTR(BILL_CODE,INSTR(BILL_CODE,'-')+1,INSTR(BILL_CODE,' ')-INSTR(BILL_CODE,'-')-1) DESC
                        ) RN
      ,SUBSTR(BILL_CODE,1,INSTR(BILL_CODE,'-')-1) AS CD_NO
      ,SUBSTR(BILL_CODE,INSTR(BILL_CODE,'-')+1,INSTR(BILL_CODE,' ')-INSTR(BILL_CODE,'-')-1) BS_NUM
      ,SUBSTR(BILL_CODE,INSTR(BILL_CODE,' ')+1) AS CD_RANGE
      ,A.*
 FROM ODS.ODSMT_FIN_BILL_VIEW_DATA@FMSLK A
 WHERE DATA_DATE = TO_CHAR(LAST_DAY(TO_DATE({IN-YEARMONTH},'YYYYMM')),'YYYYMMDD')
)
,XH_SRC AS (
SELECT
      {IN-YEARMONTH} AS YEARMONTH,                    -- 年月
      NVL(M.BUKRS,A.COD_AZIENDA) AS AP_BUKRS,      -- 应付公司
      CASE WHEN XH.HOLD_CUSTOMER_NAME = '青岛海信商业保理有限公司' 
             THEN '9002' 
          ELSE NVL(M1.BUKRS,A1.COD_AZIENDA)
      END AS AR_BUKRS, -- 应收公司
      SUM(BILL_AMOUNT) AS BILL_AMT ,                -- 票据金额
      SIGN_DATE,
      CASE WHEN SIGN_DATE IS NULL THEN 1 ELSE LAST_DAY(TO_DATE({IN-YEARMONTH},'YYYYMM')) - SIGN_DATE + 1 END  AS ZL,
      'XINHUI'     AS SRC,                          -- 来源
      SYSDATE      AS DATEUPD,                      -- 更新时间
      'SYSJOB781'  AS USERUPD                       -- 更新用户
FROM  XH
     ,TGK_GB_HISENSE.ZTAB_9000_ACCT_MAPING M  /*内部公司账户*/
     ,TGK_GB_HISENSE.ZTAB_9000_ACCT_MAPING M1
     ,TGK_GB_HISENSE.AZI A
     ,TGK_GB_HISENSE.AZI A1
 WHERE XH.RN=1
 AND XH.CREDIT_CUSTOMER_CODE    = A.SEDE_LEGALE(+)
 AND XH.CREDIT_CUSTOMER_ACCOUNT = M.ACCOUNT_NO(+)
 AND XH.RECEIVE_CREDIT_CODE     = A1.SEDE_LEGALE(+)
 AND XH.HOLD_CUSTOMER_ACCOUNT   = M1.ACCOUNT_NO(+)
 AND COALESCE(M.BUKRS,A.COD_AZIENDA,'NULL') <> NVL((CASE WHEN XH.HOLD_CUSTOMER_NAME='青岛海信商业保理有限公司' THEN '9002' ELSE NVL(M1.BUKRS,A1.COD_AZIENDA) END),'NULL')   -- 应收<>应付
 AND (XH.BILL_STATUS <> 9999)
 GROUP BY /*CD_NO,CD_RANGE,*/NVL(M.BUKRS,A.COD_AZIENDA)
         ,(CASE WHEN XH.HOLD_CUSTOMER_NAME = '青岛海信商业保理有限公司' THEN '9002' ELSE NVL(M1.BUKRS,A1.COD_AZIENDA) END)
         ,/*ISSUE_DATE,EXPIRY_DATE,*/SIGN_DATE
         ,CASE WHEN SIGN_DATE IS NULL THEN 1 ELSE LAST_DAY(TO_DATE({IN-YEARMONTH},'YYYYMM')) - SIGN_DATE END 
  HAVING SUM(BILL_AMOUNT) <> 0 
) 

SELECT 
    MANDT,BUKRS, CVCODE,HKONT,{IN-YEARMONTH} AS YEARMONTH, LCODE, 
    SUM(DMBTR) DMBTR,  
    SUM(CASE WHEN ZL<=30                 THEN DMBTR ELSE 0 END) DMBTR1, 
    SUM(CASE WHEN ZL>30   AND ZL<=90     THEN DMBTR ELSE 0 END) DMBTR2, 
    SUM(CASE WHEN ZL>90   AND ZL<=180    THEN DMBTR ELSE 0 END) DMBTR3, 
    SUM(CASE WHEN ZL>180  AND ZL<=365    THEN DMBTR ELSE 0 END) DMBTR4, 
    SUM(CASE WHEN ZL>365  AND ZL<=730    THEN DMBTR ELSE 0 END) DMBTR5, 
    SUM(CASE WHEN ZL>730  AND ZL<=1095   THEN DMBTR ELSE 0 END) DMBTR6, 
    SUM(CASE WHEN ZL>1095 AND ZL<=1460   THEN DMBTR ELSE 0 END) DMBTR7, 
    SUM(CASE WHEN ZL>1460 AND ZL<=1825   THEN DMBTR ELSE 0 END) DMBTR8, 
    SUM(CASE WHEN ZL>1825                THEN DMBTR ELSE 0 END) DMBTR9,
    SUM(DMBTR) WRBTR,  
    SUM(CASE WHEN ZL<=30                 THEN DMBTR ELSE 0 END) WRBTR1, 
    SUM(CASE WHEN ZL>30   AND ZL<=90     THEN DMBTR ELSE 0 END) WRBTR2, 
    SUM(CASE WHEN ZL>90   AND ZL<=180    THEN DMBTR ELSE 0 END) WRBTR3, 
    SUM(CASE WHEN ZL>180  AND ZL<=365    THEN DMBTR ELSE 0 END) WRBTR4, 
    SUM(CASE WHEN ZL>365  AND ZL<=730    THEN DMBTR ELSE 0 END) WRBTR5, 
    SUM(CASE WHEN ZL>730  AND ZL<=1095   THEN DMBTR ELSE 0 END) WRBTR6, 
    SUM(CASE WHEN ZL>1095 AND ZL<=1460   THEN DMBTR ELSE 0 END) WRBTR7, 
    SUM(CASE WHEN ZL>1460 AND ZL<=1825   THEN DMBTR ELSE 0 END) WRBTR8, 
    SUM(CASE WHEN ZL>1825                THEN DMBTR ELSE 0 END) WRBTR9,
    IC, CUSVEN, NAME1,KVERM ,/*'XH' RATETAG,*/'N' IS_REC,'N' IS_REC_M,'CNY' AS  HWAER ,'CNY' AS WAERS 
FROM (
/*AR*/
SELECT M.MANDT,AR_BUKRS AS  BUKRS, '1122000095' HKONT, 'AR' LCODE, AP_BUKRS AS IC, 'C' CUSVEN,'' AS KVERM, 'XH_'||NVL(AP_BUKRS,'Z001') AS CVCODE, '应收账款-信汇' AS NAME1 , SUM(T.BILL_AMT) DMBTR,T.ZL
 FROM XH_SRC T
 /*获取系统*/
 INNER JOIN (SELECT T.MANDT,T.BUKRS FROM TGK_GB_HISENSE.ZTAB_APAR_AGING_SOURCE T WHERE T.YEARMONTH >= '202301' GROUP BY T.MANDT,T.BUKRS ) M
   ON T.AR_BUKRS = M.BUKRS
 --WHERE AR_BUKRS IS NOT NULL 
 GROUP BY MANDT,AR_BUKRS,AP_BUKRS,T.ZL
 
 UNION ALL 
 /*AP*/
SELECT M.MANDT,AP_BUKRS AS  BUKRS, '2202000095' HKONT, 'AP' LCODE, AR_BUKRS AS IC, 'V' CUSVEN,'' AS KVERM, 'XH_'||NVL(AR_BUKRS,'Z001') AS CVCODE, '应付账款-信汇' AS NAME1 , -SUM(T.BILL_AMT) DMBTR,T.ZL
 FROM XH_SRC T
 /*获取系统*/
 INNER JOIN (SELECT T.MANDT,T.BUKRS FROM TGK_GB_HISENSE.ZTAB_APAR_AGING_SOURCE T WHERE T.YEARMONTH >= '202301' GROUP BY T.MANDT,T.BUKRS ) M
   ON T.AP_BUKRS = M.BUKRS
 --WHERE AP_BUKRS IS NOT NULL 
 GROUP BY MANDT,AR_BUKRS,AP_BUKRS,T.ZL
 ) T
 WHERE BUKRS IN ({IN-ENTITY})
 AND BUKRS NOT IN ('9000','9002','9003','9005','9008')
 AND {IN-YEARMONTH} >= '202607'
 GROUP BY MANDT,BUKRS,HKONT,LCODE,IC,CUSVEN, KVERM, CVCODE, NAME1
